namespace GameServer.Data.SDB;

using Records.apt;
using Records.aptfs;
using Records.dbviusalrecords;
using Records.dbitems;
using System.Collections.Generic;
using Records.dbcharacter;
using Records.vcs;

public interface ISDBLoader
{
    // dbcharacter
    Dictionary<uint, CharCreateLoadout> LoadCharCreateLoadout();
    Dictionary<uint, Dictionary<byte, CharCreateLoadoutSlots>> LoadCharCreateLoadoutSlots();
    Dictionary<uint, Deployable> LoadDeployable();
    Dictionary<uint, Monster> LoadMonster();
    Dictionary<uint, Turret> LoadTurret();

    // dbvisualrecords
    Dictionary<uint, WarpaintPalette> LoadWarpaintPalettes();

    // dbitems
    Dictionary<uint, AttributeCategory> LoadAttributeCategory();
    Dictionary<uint, AttributeDefinition> LoadAttributeDefinition();
    Dictionary<KeyValuePair<uint, ushort>, AttributeRange> LoadAttributeRange();
    Dictionary<KeyValuePair<uint, ushort>, ItemModuleScalars> LoadItemModuleScalars();
    Dictionary<KeyValuePair<uint, ushort>, ItemCharacterScalars> LoadItemCharacterScalars();
    Dictionary<uint, RootItem> LoadRootItem();
    Dictionary<uint, Battleframe> LoadBattleframe();
    Dictionary<uint, CarryableObject> LoadCarryableObject();
    Dictionary<uint, Weapons> LoadWeapons();
    Dictionary<uint, WeaponTemplates> LoadWeaponTemplates();
    Dictionary<uint, WeaponTemplateModifiers> LoadWeaponTemplateModifiers();
    Dictionary<uint, WeaponScope> LoadWeaponScope();
    Dictionary<uint, WeaponUnderbarrel> LoadWeaponUnderbarrel();
    Dictionary<uint, Ammo> LoadAmmo();

    // apt
    Dictionary<uint, BaseCommandDef> LoadBaseCommandDef();
    Dictionary<uint, CommandType> LoadCommandType();
    Dictionary<uint, AbilityData> LoadAbilityData();
    Dictionary<uint, ImpactApplyEffectCommandDef> LoadImpactApplyEffectCommandDef();
    Dictionary<uint, ConditionalBranchCommandDef> LoadConditionalBranchCommandDef();
    Dictionary<uint, WhileLoopCommandDef> LoadWhileLoopCommandDef();
    Dictionary<uint, LogicNegateCommandDef> LoadLogicNegateCommandDef();
    Dictionary<uint, LogicOrCommandDef> LoadLogicOrCommandDef();
    Dictionary<uint, LogicOrChainCommandDef> LoadLogicOrChainCommandDef();
    Dictionary<uint, LogicAndChainCommandDef> LoadLogicAndChainCommandDef();
    Dictionary<uint, CallCommandDef> LoadCallCommandDef();
    Dictionary<uint, InstantActivationCommandDef> LoadInstantActivationCommandDef();
    Dictionary<uint, StagedActivationCommandDef> LoadStagedActivationCommandDef();
    Dictionary<uint, StatusEffectData> LoadStatusEffectData();
    Dictionary<uint, TargetPBAECommandDef> LoadTargetPBAECommandDef();
    Dictionary<uint, TargetConeAECommandDef> LoadTargetConeAECommandDef();
    Dictionary<uint, TargetClearCommandDef> LoadTargetClearCommandDef();
    Dictionary<uint, TargetSelfCommandDef> LoadTargetSelfCommandDef();
    Dictionary<uint, TargetSwapCommandDef> LoadTargetSwapCommandDef();
    Dictionary<uint, TargetStackEmptyCommandDef> LoadTargetStackEmptyCommandDef();
    Dictionary<uint, TargetInitiatorCommandDef> LoadTargetInitiatorCommandDef();
    Dictionary<uint, PeekTargetsCommandDef> LoadPeekTargetsCommandDef();
    Dictionary<uint, PopTargetsCommandDef> LoadPopTargetsCommandDef();
    Dictionary<uint, PushTargetsCommandDef> LoadPushTargetsCommandDef();
    Dictionary<uint, TimeDurationCommandDef> LoadTimeDurationCommandDef();
    Dictionary<uint, AirborneDurationCommandDef> LoadAirborneDurationCommandDef();
    Dictionary<uint, ActivationDurationCommandDef> LoadActivationDurationCommandDef();
    Dictionary<uint, ReturnCommandDef> LoadReturnCommandDef();
    Dictionary<uint, LoadRegisterFromItemStatCommandDef> LoadLoadRegisterFromItemStatCommandDef();
    Dictionary<uint, LoadRegisterFromBonusCommandDef> LoadLoadRegisterFromBonusCommandDef();
    Dictionary<uint, LoadRegisterFromDamageCommandDef> LoadLoadRegisterFromDamageCommandDef();
    Dictionary<uint, LoadRegisterFromLevelCommandDef> LoadLoadRegisterFromLevelCommandDef();
    Dictionary<uint, LoadRegisterFromModulePowerCommandDef> LoadLoadRegisterFromModulePowerCommandDef();
    Dictionary<uint, LoadRegisterFromNamedVarCommandDef> LoadLoadRegisterFromNamedVarCommandDef();
    Dictionary<uint, LoadRegisterFromResourceCommandDef> LoadLoadRegisterFromResourceCommandDef();
    Dictionary<uint, LoadRegisterFromStatCommandDef> LoadLoadRegisterFromStatCommandDef();
    Dictionary<uint, RegisterComparisonCommandDef> LoadRegisterComparisonCommandDef();
    Dictionary<uint, RegisterRandomCommandDef> LoadRegisterRandomCommandDef();
    Dictionary<uint, SetRegisterCommandDef> LoadSetRegisterCommandDef();
    Dictionary<uint, NamedVariableAssignCommandDef> LoadNamedVariableAssignCommandDef();
    Dictionary<uint, InflictCooldownCommandDef> LoadInflictCooldownCommandDef();
    Dictionary<uint, RequireDamageTypeCommandDef> LoadRequireDamageTypeCommandDef();
    Dictionary<uint, TargetSingleCommandDef> LoadTargetSingleCommandDef();
    Dictionary<uint, TimeCooldownCommandDef> LoadTimeCooldownCommandDef();
    Dictionary<uint, TimedActivationCommandDef> LoadTimedActivationCommandDef();
    Dictionary<uint, PassiveInitiationCommandDef> LoadPassiveInitiationCommandDef();
    Dictionary<uint, TargetPreviousCommandDef> LoadTargetPreviousCommandDef();
    Dictionary<uint, UpdateYieldCommandDef> LoadUpdateYieldCommandDef();
    Dictionary<uint, TargetDifferenceCommandDef> LoadTargetDifferenceCommandDef();
    Dictionary<uint, AimRangeDurationCommandDef> LoadAimRangeDurationCommandDef();
    Dictionary<uint, TargetTrimCommandDef> LoadTargetTrimCommandDef();
    Dictionary<uint, BonusGreaterThanCommandDef> LoadBonusGreaterThanCommandDef();
    Dictionary<uint, UpdateWaitCommandDef> LoadUpdateWaitCommandDef();
    Dictionary<uint, PushRegisterCommandDef> LoadPushRegisterCommandDef();
    Dictionary<uint, PopRegisterCommandDef> LoadPopRegisterCommandDef();
    Dictionary<uint, PeekRegisterCommandDef> LoadPeekRegisterCommandDef();
    Dictionary<uint, UpdateWaitAndFireOnceCommandDef> LoadUpdateWaitAndFireOnceCommandDef();
    Dictionary<uint, RegisterLoadScaleCommandDef> LoadRegisterLoadScaleCommandDef();

    // aptfs
    Dictionary<uint, TargetFriendliesCommandDef> LoadTargetFriendliesCommandDef();
    Dictionary<uint, TargetByEffectCommandDef> LoadTargetByEffectCommandDef();
    Dictionary<uint, TargetByEffectTagCommandDef> LoadTargetByEffectTagCommandDef();
    Dictionary<uint, TargetOwnerCommandDef> LoadTargetOwnerCommandDef();
    Dictionary<uint, TargetByObjectTypeCommandDef> LoadTargetByObjectTypeCommandDef();
    Dictionary<uint, TargetHostilesCommandDef> LoadTargetHostilesCommandDef();
    Dictionary<uint, TargetByCharacterStateCommandDef> LoadTargetByCharacterStateCommandDef();
    Dictionary<uint, InflictDamageCommandDef> LoadInflictDamageCommandDef();
    Dictionary<uint, ForcePushCommandDef> LoadForcePushCommandDef();
    Dictionary<uint, RequestBattleFrameListCommandDef> LoadRequestBattleFrameListCommandDef();
    Dictionary<uint, ApplyImpulseCommandDef> LoadApplyImpulseCommandDef();
    Dictionary<uint, DeployableCalldownCommandDef> LoadDeployableCalldownCommandDef();
    Dictionary<uint, FireProjectileCommandDef> LoadFireProjectileCommandDef();
    Dictionary<uint, ResourceNodeBeaconCalldownCommandDef> LoadResourceNodeBeaconCalldownCommandDef();
    Dictionary<uint, AttemptToCalldownVehicleCommandDef> LoadAttemptToCalldownVehicleCommandDef();
    Dictionary<uint, VehicleCalldownCommandDef> LoadVehicleCalldownCommandDef();
    Dictionary<uint, RegisterClientProximityCommandDef> LoadRegisterClientProximityCommandDef();
    Dictionary<uint, CombatFlagsCommandDef> LoadCombatFlagsCommandDef();
    Dictionary<uint, ApplyFreezeCommandDef> LoadApplyFreezeCommandDef();
    Dictionary<uint, OrientationLockCommandDef> LoadOrientationLockCommandDef();
    Dictionary<uint, StatModifierCommandDef> LoadStatModifierCommandDef();
    Dictionary<uint, RequireAimModeCommandDef> LoadRequireAimModeCommandDef();
    Dictionary<uint, RequireArmyCommandDef> LoadRequireArmyCommandDef();
    Dictionary<uint, RequireBackstabCommandDef> LoadRequireBackstabCommandDef();
    Dictionary<uint, RequireBulletHitCommandDef> LoadRequireBulletHitCommandDef();
    Dictionary<uint, RequireCAISStateCommandDef> LoadRequireCAISStateCommandDef();
    Dictionary<uint, RequireCStateCommandDef> LoadRequireCStateCommandDef();
    Dictionary<uint, RequireDamageResponseCommandDef> LoadRequireDamageResponseCommandDef();
    Dictionary<uint, RequireEliteLevelCommandDef> LoadRequireEliteLevelCommandDef();
    Dictionary<uint, RequireEnergyByRangeCommandDef> LoadRequireEnergyByRangeCommandDef();
    Dictionary<uint, RequireEnergyCommandDef> LoadRequireEnergyCommandDef();
    Dictionary<uint, RequireEnergyFromTargetCommandDef> LoadRequireEnergyFromTargetCommandDef();
    Dictionary<uint, RequireEquippedItemCommandDef> LoadRequireEquippedItemCommandDef();
    Dictionary<uint, RequireFriendsCommandDef> LoadRequireFriendsCommandDef();
    Dictionary<uint, RequireHasCertificateCommandDef> LoadRequireHasCertificateCommandDef();
    Dictionary<uint, RequireHasEffectCommandDef> LoadRequireHasEffectCommandDef();
    Dictionary<uint, RequireHasEffectTagCommandDef> LoadRequireHasEffectTagCommandDef();
    Dictionary<uint, RequireHasItemCommandDef> LoadRequireHasItemCommandDef();
    Dictionary<uint, RequireHasUnlockCommandDef> LoadRequireHasUnlockCommandDef();
    Dictionary<uint, RequireHeadshotCommandDef> LoadRequireHeadshotCommandDef();
    Dictionary<uint, RequireInCombatCommandDef> LoadRequireInCombatCommandDef();
    Dictionary<uint, RequireInRangeCommandDef> LoadRequireInRangeCommandDef();
    Dictionary<uint, RequireInVehicleCommandDef> LoadRequireInVehicleCommandDef();
    Dictionary<uint, RequireIsNPCCommandDef> LoadRequireIsNPCCommandDef();
    Dictionary<uint, RequireItemAttributeCommandDef> LoadRequireItemAttributeCommandDef();
    Dictionary<uint, RequireItemDurabilityCommandDef> LoadRequireItemDurabilityCommandDef();
    Dictionary<uint, RequireJumpedCommandDef> LoadRequireJumpedCommandDef();
    Dictionary<uint, RequireLevelCommandDef> LoadRequireLevelCommandDef();
    Dictionary<uint, RequireLineOfSightCommandDef> LoadRequireLineOfSightCommandDef();
    Dictionary<uint, RequirementServerCommandDef> LoadRequirementServerCommandDef();
    Dictionary<uint, RequireMovementFlagsCommandDef> LoadRequireMovementFlagsCommandDef();
    Dictionary<uint, RequireMovestateCommandDef> LoadRequireMovestateCommandDef();
    Dictionary<uint, RequireMovingCommandDef> LoadRequireMovingCommandDef();
    Dictionary<uint, RequireNeedsAmmoCommandDef> LoadRequireNeedsAmmoCommandDef();
    Dictionary<uint, RequireNotRespawnedCommandDef> LoadRequireNotRespawnedCommandDef();
    Dictionary<uint, RequirePermissionCommandDef> LoadRequirePermissionCommandDef();
    Dictionary<uint, RequireProjectileSlopeCommandDef> LoadRequireProjectileSlopeCommandDef();
    Dictionary<uint, RequireReloadCommandDef> LoadRequireReloadCommandDef();
    Dictionary<uint, RequireResourceCommandDef> LoadRequireResourceCommandDef();
    Dictionary<uint, RequireResourceFromTargetCommandDef> LoadRequireResourceFromTargetCommandDef();
    Dictionary<uint, RequireSinAcquiredCommandDef> LoadRequireSinAcquiredCommandDef();
    Dictionary<uint, RequireSprintModifierCommandDef> LoadRequireSprintModifierCommandDef();
    Dictionary<uint, RequireSquadLeaderCommandDef> LoadRequireSquadLeaderCommandDef();
    Dictionary<uint, RequireSuperChargeCommandDef> LoadRequireSuperChargeCommandDef();
    Dictionary<uint, RequireTookDamageCommandDef> LoadRequireTookDamageCommandDef();
    Dictionary<uint, RequireWeaponArmedCommandDef> LoadRequireWeaponArmedCommandDef();
    Dictionary<uint, RequireWeaponTemplateCommandDef> LoadRequireWeaponTemplateCommandDef();
    Dictionary<uint, RequireZoneTypeCommandDef> LoadRequireZoneTypeCommandDef();
    Dictionary<uint, InteractionTypeCommandDef> LoadInteractionTypeCommandDef();
    Dictionary<uint, TargetInteractivesCommandDef> LoadTargetInteractivesCommandDef();
    Dictionary<uint, ImpactMarkInteractivesCommandDef> LoadImpactMarkInteractivesCommandDef();
    Dictionary<uint, HasTargetsDurationCommandDef> LoadHasTargetsDurationCommandDef();
    Dictionary<uint, RopePullCommandDef> LoadRopePullCommandDef();
    Dictionary<uint, SetTargetOffsetCommandDef> LoadSetTargetOffsetCommandDef();
    Dictionary<uint, HealDamageCommandDef> LoadHealDamageCommandDef();
    Dictionary<uint, BullrushCommandDef> LoadBullrushCommandDef();
    Dictionary<uint, EnergyToDamageCommandDef> LoadEnergyToDamageCommandDef();
    Dictionary<uint, BattleFrameDurationCommandDef> LoadBattleFrameDurationCommandDef();
    Dictionary<uint, ShootingDurationCommandDef> LoadShootingDurationCommandDef();
    Dictionary<uint, SwitchWeaponCommandDef> LoadSwitchWeaponCommandDef();
    Dictionary<uint, StatRequirementCommandDef> LoadStatRequirementCommandDef();
    Dictionary<uint, ConsumeEnergyCommandDef> LoadConsumeEnergyCommandDef();
    Dictionary<uint, TargetClassTypeCommandDef> LoadTargetClassTypeCommandDef();
    Dictionary<uint, ClimbLedgeCommandDef> LoadClimbLedgeCommandDef();
    Dictionary<uint, CopyInitiationPositionCommandDef> LoadCopyInitiationPositionCommandDef();
    Dictionary<uint, SlotAmmoCommandDef> LoadSlotAmmoCommandDef();
    Dictionary<uint, AddPhysicsCommandDef> LoadAddPhysicsCommandDef();
    Dictionary<uint, TargetCurrentVehicleCommandDef> LoadTargetCurrentVehicleCommandDef();
    Dictionary<uint, TargetPassengersCommandDef> LoadTargetPassengersCommandDef();
    Dictionary<uint, TargetSquadmatesCommandDef> LoadTargetSquadmatesCommandDef();
    Dictionary<uint, SetWeaponDamageCommandDef> LoadSetWeaponDamageCommandDef();
    Dictionary<uint, ConsumeEnergyOverTimeCommandDef> LoadConsumeEnergyOverTimeCommandDef();
    Dictionary<uint, RequestAbilitySelectionCommandDef> LoadRequestAbilitySelectionCommandDef();
    Dictionary<uint, BombardmentCommandDef> LoadBombardmentCommandDef();
    Dictionary<uint, SetProjectileTargetCommandDef> LoadSetProjectileTargetCommandDef();
    Dictionary<uint, MovementSlideCommandDef> LoadMovementSlideCommandDef();
    Dictionary<uint, TargetFromStatusEffectCommandDef> LoadTargetFromStatusEffectCommandDef();
    Dictionary<uint, TargetByDamageResponseCommandDef> LoadTargetByDamageResponseCommandDef();
    Dictionary<uint, ForcedMovementDurationCommandDef> LoadForcedMovementDurationCommandDef();
    Dictionary<uint, FireUiEventCommandDef> LoadFireUiEventCommandDef();
    Dictionary<uint, UiNamedVariableCommandDef> LoadUiNamedVariableCommandDef();
    Dictionary<uint, DetonateProjectilesCommandDef> LoadDetonateProjectilesCommandDef();
    Dictionary<uint, SetWeaponDamageTypeCommandDef> LoadSetWeaponDamageTypeCommandDef();
    Dictionary<uint, TargetFilterMovestateCommandDef> LoadTargetFilterMovestateCommandDef();
    Dictionary<uint, TargetByHostilityCommandDef> LoadTargetByHostilityCommandDef();
    Dictionary<uint, ConsumeSuperChargeCommandDef> LoadConsumeSuperChargeCommandDef();
    Dictionary<uint, TargetByHealthCommandDef> LoadTargetByHealthCommandDef();
    Dictionary<uint, RegisterMovementEffectCommandDef> LoadRegisterMovementEffectCommandDef();
    Dictionary<uint, ApplyAmmoRiderCommandDef> LoadApplyAmmoRiderCommandDef();
    Dictionary<uint, TargetFilterByRangeCommandDef> LoadTargetFilterByRangeCommandDef();
    Dictionary<uint, OverrideCollisionCommandDef> LoadOverrideCollisionCommandDef();
    Dictionary<uint, MovementFacingCommandDef> LoadMovementFacingCommandDef();
    Dictionary<uint, TargetFilterBySinAcquiredCommandDef> LoadTargetFilterBySinAcquiredCommandDef();
    Dictionary<uint, MovementTetherCommandDef> LoadMovementTetherCommandDef();
    Dictionary<uint, RegisterLoadFromWeaponCommandDef> LoadRegisterLoadFromWeaponCommandDef();
    Dictionary<uint, ApplyClientStatusEffectCommandDef> LoadApplyClientStatusEffectCommandDef();
    Dictionary<uint, RemoveClientStatusEffectCommandDef> LoadRemoveClientStatusEffectCommandDef();
    Dictionary<uint, DisableChatBubbleCommandDef> LoadDisableChatBubbleCommandDef();
    Dictionary<uint, DisableHealthAndIconCommandDef> LoadDisableHealthAndIconCommandDef();

    // vcs
    Dictionary<byte, VehicleClass> LoadVehicleClass();
    Dictionary<ushort, VehicleInfo> LoadVehicleInfo();
    Dictionary<ushort, Dictionary<uint, BaseComponentDef>> LoadBaseComponentDef();
    Dictionary<uint, ScopingComponentDef> LoadScopingComponentDef();
    Dictionary<uint, DriverComponentDef> LoadDriverComponentDef();
    Dictionary<uint, PassengerComponentDef> LoadPassengerComponentDef();
    Dictionary<uint, AbilityComponentDef> LoadAbilityComponentDef();
    Dictionary<uint, DamageComponentDef> LoadDamageComponentDef();
    Dictionary<uint, StatusEffectComponentDef> LoadStatusEffectComponentDef();
    Dictionary<uint, TurretComponentDef> LoadTurretComponentDef();
    Dictionary<uint, DeployableComponentDef> LoadDeployableComponentDef();
    Dictionary<uint, SpawnPointComponentDef> LoadSpawnPointComponentDef();
}