<Project>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13.0</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(MSBuildProjectName)' != 'AeroMessages' And
                              '$(MSBuildProjectName)' != 'BepuPhysics' And
                              '$(MSBuildProjectName)' != 'BepuUtilities'">
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)/stylecop.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    <PropertyGroup>
        <Company>The Melding Wars</Company>
        <Copyright>Copyright © 2019-2026 by The Melding Wars</Copyright>
        <Product>Pirate Intelligence Network</Product>
    </PropertyGroup>
    <PropertyGroup Condition="'$(MSBuildProjectName)' != 'AeroMessages' And
                              '$(MSBuildProjectName)' != 'BepuPhysics' And
                              '$(MSBuildProjectName)' != 'BepuUtilities'">
        <Authors>The Melding Wars</Authors>
        <NeutralLanguage>en-US</NeutralLanguage>
        <RepositoryUrl>https://github.com/themeldingwars/PIN</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>
    <ItemGroup Condition="'$(MSBuildProjectName)' != 'AeroMessages' And
                          '$(MSBuildProjectName)' != 'BepuPhysics' And
                          '$(MSBuildProjectName)' != 'BepuUtilities'">
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>