<Project>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13.0</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(MSBuildProjectName)' != 'AeroMessages' And
                              '$(MSBuildProjectName)' != 'BepuPhysics' And
                              '$(MSBuildProjectName)' != 'BepuUtilities'">
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)/stylecop.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    <PropertyGroup>
        <Version>1.2.0</Version>
        <Company>The Melding Wars</Company>
        <Copyright>Copyright © 2019-2026 by The Melding Wars</Copyright>
        <Product>Pirate Intelligence Network</Product>
    </PropertyGroup>
</Project>