using System;
using System.Collections.Generic;
using System.Text;

namespace MyGameServer.Packets {
    public enum ControlPacketType : byte {
        CloseConnection = 0,
        MatrixAck = 2,
        ReliableGSSAck = 3,
        TimeSyncRequest = 4,
        TimeSyncResponse = 5,
        MTUProbe = 6
    }

    public enum MatrixPacketType : byte {
        Login = 17,
        EnterZoneAck = 18,
        ExitZoneAck = 19,
        KeyframeRequest = 20,
        DEV_ExecuteCommand = 21,
        Referee_ExecuteCommand = 22,
        RequestPause = 23,
        RequestResume = 24,
        ClientStatus = 25,
        ClientPreferences = 26,
        SynchronizationResponse = 27,
        SuperPing = 28,
        StressTestMasterObject = 29,
        ServerProfiler_RequestNames = 30,
        LogInstrumentation = 31,
        RequestSigscan = 32,
        SendEmergencyChat = 33,
        SigscanData = 34,
        WelcomeToTheMatrix = 35,
        Announce = 36,
        EnterZone = 37,
        UpdateZoneTimeSync = 38,
        HotfixLevelChanged = 39,
        ExitZone = 40,
        MatrixStatus = 41,
        MatchQueueResponse = 42,
        MatchQueueUpdate = 43,
        FoundMatchUpdate = 44,
        ChallengeJoinResponse = 45,
        ChallengeInvitation = 46,
        ChallengeInvitationSquadInfoAck = 47,
        ChallengeInvitationCancel = 48,
        ChallengeInvitationResponse = 49,
        ChallengeKicked = 50,
        ChallengeLeave = 51,
        ChallengeRosterUpdate = 52,
        ChallengeReadyCheck = 53,
        ChallengeMatchParametersUpdate = 54,
        ChallengeMatchStarting = 55,
        ForceUnqueue = 56,
        SynchronizationRequest = 57,
        GamePaused = 58,
        SuperPong = 59,
        ServerProfiler_SendNames = 60,
        ServerProfiler_SendFrame = 61,
        ZoneQueueUpdate = 62,
        DebugLagSampleSim = 63,
        DebugLagSampleClient = 64,
        LFGMatchFound = 65,
        LFGLeaderChange = 66,
        ReceiveEmergencyChat = 67,
        UpdateDevZoneInfo = 68,
    }

    namespace GSS {
		public enum Controllers : byte {
			Generic = 0,
		}

		public enum GenericEvents : byte {
			EncounterToUIMessage = 32,
			VotekickInitiated = 33,
			VotekickResponded = 34,
			ScoreBoardEnable = 35,
			ScoreBoardInit = 36,
			ScoreBoardSetWinner = 37,
			ScoreBoardClear = 38,
			ScoreBoardAddPlayer = 39,
			ScoreBoardRemovePlayer = 40,
			ScoreBoardUpdatePlayerStats = 41,
			ScoreBoardUpdatePlayerStatsFromStat = 42,
			ScoreBoardUpdatePlayerStatus = 43,
			MatchLoadingState = 44,
			MatchEndAck = 45,
			ServerProfiler_SendNames = 46,
			ServerProfiler_SendFrame = 47,
			TempConsoleMessage = 48,
			ReloadStaticData = 49,
			EncDebugChatMessage = 50,
			SendRadioMessage = 51,
			NpcBehaviorInfo = 52,
			NpcMonitoringLog = 53,
			NpcNavigationInfo = 54,
			NpcHostilityDebugInfo = 55,
			NpcPositionalDebugInfo = 56,
			NpcShapeDebugInfo = 57,
			NpcVoxelInfo = 58,
			DebugDrawInfo = 59,
			NpcDevCmdResponse = 60,
			DevRequestObjectPositions = 61,
			DevRequestSpawnTables = 62,
			DevRequestResourceNodeDebug = 63,
			MissionObjectiveUpdated = 64,
			MissionStatusChanged = 65,
			MissionReturnToChanged = 66,
			MissionsAvailable = 67,
			MissionActivationAck = 68,
			BountyStatusChanged = 69,
			BountyAbortAck = 70,
			BountyActivationAck = 71,
			BountyListActiveAck = 72,
			BountyListActiveDetailsAck = 73,
			BountyListAvailableAck = 74,
			BountyClearAck = 75,
			BountyClearPreviousAck = 76,
			BountyListPreviousAck = 77,
			BountyRerollResponse = 78,
			DisplayUiTrackBounty = 79,
			Achievements = 80,
			AchievementUnlocked = 81,
			TotalAchievementPoints = 82,
			MissionCompletionCounts = 83,
			ContentUnlocked = 84,
			ClientUIAction = 85,
			ArcCompletionHistoryUpdate = 86,
			JobLedgerEntriesUpdate = 87,
			TrackRecipe = 88,
			ClearTrackedRecipe = 89,
			SlotTech = 90,
			InteractableStatusChanged = 91,
			SendTipMessage = 92,
			DebugEventSample = 93,
			DebugLagPlayerSample = 94,
			DebugLagSimulationSample = 95,
			DebugLagRaiaSample = 96,
			DebugEncounterVolumes = 97,
			Trail = 98,
			EncounterDebugNotification = 99,
			EncounterUIScopeIn = 100,
			EncounterUIUpdate = 101,
			EncounterUIScopeOut = 102,
			DisplayUiNotification = 103,
			DisplayMoneyBombBanner = 104,
			SetPreloadPosition = 105,
			PlaySoundId = 106,
			PlaySoundIdAtLocation = 107,
			PlayDialogScriptMessage = 108,
			StopDialogScriptMessage = 109,
			PingMap = 110,
			PingMapMarker = 111,
			EncounterPublicInfo = 112,
			RequestActiveEncounters_Respons = 113,
			ShoppingListInit = 114,
			SetClientDailyInfo = 115,
			GlobalCounterUpdate = 116,
			GlobalCounterMilestoneInfo = 117,
			ChatMessageList = 118,
			CurrentLoadoutResponse = 119,
			VendorProductsResponse = 120,
			VendorPurchaseResponse = 121,
			ConductorGlobalAnnouncement = 122,
		}

		public enum GenericCommands : byte {
			UIToEncounterMessage = 17,
			ServerProfiler_RequestNames = 18,
			ScheduleUpdateRequest = 19,
			LocalProximityAbilitySuccess = 20,
			RemoteProximityAbilitySuccess = 21,
			TrailRequest = 22,
			RequestLeaveZone = 23,
			RequestLogout = 24,
			RequestEncounterInfo = 25,
			RequestActiveEncounters = 26,
			VotekickRequest = 27,
			VotekickResponse = 28,
			GlobalCounterRequest = 29,
			CurrentLoadoutRequest = 30,
			VendorProductReques = 31,
		}
	}
}
