services:
    seq:
        container_name: PIN.Seq
        image: datalust/seq
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SEQ_FIRSTRUN_NOAUTHENTICATION=True
        ports:
            - "8081:80"
            - "5341:5341"
        volumes:
            - seq_data:/data

volumes:
    seq_data:
