namespace GameServer.Data.SDB.Records.dbitems;
public record class Ammo
{
    public uint Flags { get; set; }
    public float FluidVisualStartWidth { get; set; }
    public int FlakDurationMax { get; set; }
    public float DrunkMissileFrequency { get; set; }
    public uint AbilityId { get; set; }
    public uint HomingBeamFx { get; set; }
    public uint BounceDuration { get; set; }
    public uint FluidVisualRibbonEffectId { get; set; }
    public float DrunkMissileAmplitude { get; set; }
    public float FluidVisualEndWidth { get; set; }
    public uint TouchAbilityId { get; set; }
    public float AirburstFxScale { get; set; }
    public int FlakDurationMin { get; set; }
    public float RagdollCastRadius { get; set; }
    public uint FlightFxId { get; set; }
    public uint TouchPfxId { get; set; }
    public uint AirburstFxId { get; set; }
    public uint FluidVisualMaterialId { get; set; }
    public float Gravity { get; set; }
    public float MinSpeed { get; set; }
    public uint BounceFxId { get; set; }
    public uint FlakDurationArming { get; set; }
    public int HitboxHp { get; set; }
    public uint FlightFx1stPersonId { get; set; }
    public float DamageDecayRangefrac { get; set; }
    public float BounceFriction { get; set; }
    public uint PeriodAbilityId { get; set; }
    public float HitboxRadius { get; set; }
    public float BounceElasticity { get; set; }
    public float MinDamageFrac { get; set; }
    public float IgnoreTeammatesRange { get; set; }
    public float ProjectileSpeed { get; set; }
    public float MinImpactRadius { get; set; }
    public float HomingStrength { get; set; }
    public float HitsplatFxScale { get; set; }
    public uint HitsplatMaterialEffectId { get; set; }
    public float ImpactDowncastRange { get; set; }
    public float SlopeBounceCos { get; set; }
    public uint DecalMaterialEffectId { get; set; }
    public uint ImpactFxId { get; set; }
    public uint AirburstAbilityId { get; set; }
    public float FlightFxScale { get; set; }
    public float DrunkMissileDecayRangefrac { get; set; }
    public float FireElevation { get; set; }
    public float ImpactRadius { get; set; }
    public uint TracerFreq { get; set; }
    public uint PeriodAbilityMs { get; set; }
    public float BounceCos { get; set; }
    public uint ConstLifetime { get; set; }
    public float MaxRadius { get; set; }
    public string Name { get; set; }
    public uint PeriodDamageMs { get; set; }
    public float InitialRadius { get; set; }
    public float FluidVisualTesselationDist { get; set; }
    public uint HitsplatFxId { get; set; }
    public float RadiusDt { get; set; }
    public uint MaxHits { get; set; }
    public uint Id { get; set; }
    public float ImpactFxScale { get; set; }
    public uint ParticleMaterialEffectId { get; set; }
    public uint PeriodTouchPfxMs { get; set; }
    public ushort ImpactRadiusStat { get; set; }
    public ushort ProjectileSpeedStat { get; set; }
    public ushort MaxRadiusStat { get; set; }
    public byte MaxBounces { get; set; }
    public byte ApprovalState { get; set; }
    public byte DamageDecay { get; set; }
    public byte DynamicBehavior { get; set; }
    public byte Damagetype { get; set; }
    public byte DamageResponse { get; set; }
}
