using System.Diagnostics.CodeAnalysis;

namespace GameServer.Enums;

[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:EnumerationItemsMustBeDocumented", Justification = "https://github.com/themeldingwars/Documentation/wiki/Messages-Matrix")]
public enum MatrixPacketType : byte
{
    Login = 17,
    EnterZoneAck = 18,
    ExitZoneAck = 19,
    KeyframeRequest = 20,
    DEV_ExecuteCommand = 21,
    Referee_ExecuteCommand = 22,
    RequestPause = 23,
    RequestResume = 24,
    ClientStatus = 25,
    ClientPreferences = 26,
    SynchronizationResponse = 27,
    SuperPing = 28,
    StressTestMasterObject = 29,
    ServerProfiler_RequestNames = 30,
    LogInstrumentation = 31,
    RequestSigscan = 32,
    SendEmergencyChat = 33,
    SigscanData = 34,
    WelcomeToTheMatrix = 35,
    Announce = 36,
    EnterZone = 37,
    UpdateZoneTimeSync = 38,
    HotfixLevelChanged = 39,
    ExitZone = 40,
    MatrixStatus = 41,
    MatchQueueResponse = 42,
    MatchQueueUpdate = 43,
    FoundMatchUpdate = 44,
    ChallengeJoinResponse = 45,
    ChallengeInvitation = 46,
    ChallengeInvitationSquadInfoAck = 47,
    ChallengeInvitationCancel = 48,
    ChallengeInvitationResponse = 49,
    ChallengeKicked = 50,
    ChallengeLeave = 51,
    ChallengeRosterUpdate = 52,
    ChallengeReadyCheck = 53,
    ChallengeMatchParametersUpdate = 54,
    ChallengeMatchStarting = 55,
    ForceUnqueue = 56,
    SynchronizationRequest = 57,
    GamePaused = 58,
    SuperPong = 59,
    ServerProfiler_SendNames = 60,
    ServerProfiler_SendFrame = 61,
    ZoneQueueUpdate = 62,
    DebugLagSampleSim = 63,
    DebugLagSampleClient = 64,
    LFGMatchFound = 65,
    LFGLeaderChange = 66,
    ReceiveEmergencyChat = 67,
    UpdateDevZoneInfo = 68
}