using GameServer.StaticDB.Records.customdata.Encounters;

namespace GameServer.StaticDB;

using System.Collections.Generic;
using Records.customdata;

public class CustomDBInterface
{
    // aptgss
    private static Dictionary<uint, AuthorizeTerminalCommandDef> _authorizeTerminalCommandDef;
    private static Dictionary<uint, SetGliderParametersCommandDef> _setGliderParametersCommandDef;
    private static Dictionary<uint, ModifyPermissionCommandDef> _modifyPermissionCommandDef;
    private static Dictionary<uint, ImpactRemoveEffectCommandDef> _impactRemoveEffectCommandDef;
    private static Dictionary<uint, DeployableSpawnCommandDef> _deployableSpawnCommandDef;
    private static Dictionary<uint, EncounterSignalCommandDef> _encounterSignalCommandDef;
    private static Dictionary<uint, EncounterSpawnCommandDef> _encounterSpawnCommandDef;
    private static Dictionary<uint, MountVehicleCommandDef> _mountVehicleCommandDef;
    private static Dictionary<uint, CarryableObjectSpawnCommandDef> _carryableObjectSpawnCommandDef;
    private static Dictionary<uint, ApplySinCardCommandDef> _applySinCardCommandDef;
    private static Dictionary<uint, CreateSpawnPointCommandDef> _createSpawnPointCommandDef;
    private static Dictionary<uint, AbilityFinishedCommandDef> _abilityFinishedCommandDef;
    private static Dictionary<uint, ActivateAbilityTriggerCommandDef> _activateAbilityTriggerCommandDef;
    private static Dictionary<uint, AddAccountGroupCommandDef> _addAccountGroupCommandDef;
    private static Dictionary<uint, AddAppendageHealthPoolCommandDef> _addAppendageHealthPoolCommandDef;
    private static Dictionary<uint, AddFactionReputationCommandDef> _addFactionReputationCommandDef;
    private static Dictionary<uint, AddLootTableCommandDef> _addLootTableCommandDef;
    private static Dictionary<uint, AbilitySlottedCommandDef> _abilitySlottedCommandDef;
    private static Dictionary<uint, ActivateMissionCommandDef> _activateMissionCommandDef;
    private static Dictionary<uint, ActivateSpawnTableCommandDef> _activateSpawnTableCommandDef;
    private static Dictionary<uint, CancelRopePullCommandDef> _cancelRopePullCommandDef;
    private static Dictionary<uint, CreateAbilityObjectCommandDef> _createAbilityObjectCommandDef;
    private static Dictionary<uint, DeployableUpgradeCommandDef> _deployableUpgradeCommandDef;
    private static Dictionary<uint, DestroyAbilityObjectCommandDef> _destroyAbilityObjectCommandDef;
    private static Dictionary<uint, ExecuteCommandDef> _executeCommandDef;
    private static Dictionary<uint, InteractionCompletionTimeCommandDef> _interactionCompletionTimeCommandDef;
    private static Dictionary<uint, InteractionInProgressCommandDef> _interactionInProgressCommandDef;
    private static Dictionary<uint, InterruptCommandDef> _interruptCommandDef;
    private static Dictionary<uint, LifespanDurationCommandDef> _lifespanDurationCommandDef;
    private static Dictionary<uint, MatchMakingQueueCommandDef> _matchMakingQueueCommandDef;
    private static Dictionary<uint, NPCBehaviorChangeCommandDef> _nPCBehaviorChangeCommandDef;
    private static Dictionary<uint, NPCDespawnCommandDef> _nPCDespawnCommandDef;
    private static Dictionary<uint, NPCDroidModeChangeCommandDef> _nPCDroidModeChangeCommandDef;
    private static Dictionary<uint, NPCEquipMonsterCommandDef> _nPCEquipMonsterCommandDef;
    private static Dictionary<uint, NPCSpawnCommandDef> _nPCSpawnCommandDef;
    private static Dictionary<uint, RequireTryingToMoveCommandDef> _requireTryingToMoveCommandDef;
    private static Dictionary<uint, ResetTraumaCommandDef> _resetTraumaCommandDef;
    private static Dictionary<uint, RestockAmmoCommandDef> _restockAmmoCommandDef;
    private static Dictionary<uint, ReviveCommandDef> _reviveCommandDef;
    private static Dictionary<uint, RewardAssistCommandDef> _rewardAssistCommandDef;
    private static Dictionary<uint, SetHostilityCommandDef> _setHostilityCommandDef;
    private static Dictionary<uint, SetHoverParametersCommandDef> _setHoverParametersCommandDef;
    private static Dictionary<uint, SetObjectLifespanCommandDef> _setObjectLifespanCommandDef;
    private static Dictionary<uint, SetOrientationCommandDef> _setOrientationCommandDef;
    private static Dictionary<uint, SetRespawnFlagsCommandDef> _setRespawnFlagsCommandDef;
    private static Dictionary<uint, SetYawCommandDef> _setYawCommandDef;
    private static Dictionary<uint, SinLinkRevealCommandDef> _sinLinkRevealCommandDef;
    private static Dictionary<uint, SlotAbilityCommandDef> _slotAbilityCommandDef;
    private static Dictionary<uint, TargetByExistsCommandDef> _targetByExistsCommandDef;
    private static Dictionary<uint, TargetByNPCCommandDef> _targetByNPCCommandDef;
    private static Dictionary<uint, TargetByNPCTypeCommandDef> _targetByNPCTypeCommandDef;
    private static Dictionary<uint, TargetCharacterNPCsCommandDef> _targetCharacterNPCsCommandDef;
    private static Dictionary<uint, TargetTinyObjectCommandDef> _targetTinyObjectCommandDef;
    private static Dictionary<uint, TeleportInstanceCommandDef> _teleportInstanceCommandDef;
    private static Dictionary<uint, TinyObjectCreateCommandDef> _tinyObjectCreateCommandDef;
    private static Dictionary<uint, TinyObjectDestroyCommandDef> _tinyObjectDestroyCommandDef;
    private static Dictionary<uint, TinyObjectUpdateCommandDef> _tinyObjectUpdateCommandDef;
    private static Dictionary<uint, TurretControlCommandDef> _turretControlCommandDef;
    private static Dictionary<uint, UpdateSpawnTableCommandDef> _updateSpawnTableCommandDef;
    private static Dictionary<uint, ApplyPermanentEffectCommandDef> _applyPermanentEffectCommandDef;
    private static Dictionary<uint, ApplyUnlockCommandDef> _applyUnlockCommandDef;
    private static Dictionary<uint, AwardRedBeansCommandDef> _awardRedBeansCommandDef;
    private static Dictionary<uint, CalculateTrajectoryCommandDef> _calculateTrajectoryCommandDef;
    private static Dictionary<uint, CalldownVehicleCommandDef> _calldownVehicleCommandDef;
    private static Dictionary<uint, ClearHostilityCommandDef> _clearHostilityCommandDef;
    private static Dictionary<uint, ConsumeItemCommandDef> _consumeItemCommandDef;
    private static Dictionary<uint, DamageFeedbackCommandDef> _damageFeedbackCommandDef;
    private static Dictionary<uint, DamageItemSlotCommandDef> _damageItemSlotCommandDef;
    private static Dictionary<uint, DropAllCarryableCommandDef> _dropAllCarryableCommandDef;
    private static Dictionary<uint, DropCarryableCommandDef> _dropCarryableCommandDef;
    private static Dictionary<uint, EnableInteractionCommandDef> _enableInteractionCommandDef;
    private static Dictionary<uint, EquipLoadoutCommandDef> _equipLoadoutCommandDef;
    private static Dictionary<uint, FallToGroundCommandDef> _fallToGroundCommandDef;
    private static Dictionary<uint, ForceRespawnCommandDef> _forceRespawnCommandDef;
    private static Dictionary<uint, GrantOwnerItemCommandDef> _grantOwnerItemCommandDef;
    private static Dictionary<uint, HostilityHackCommandDef> _hostilityHackCommandDef;
    private static Dictionary<uint, HostilityOverrideCommandDef> _hostilityOverrideCommandDef;
    private static Dictionary<uint, InflictHitFeedbackCommandDef> _inflictHitFeedbackCommandDef;
    private static Dictionary<uint, ItemAttributeModifierCommandDef> _itemAttributeModifierCommandDef;
    private static Dictionary<uint, MeldingBubbleCommandDef> _meldingBubbleCommandDef;
    private static Dictionary<uint, MindControlCommandDef> _mindControlCommandDef;
    private static Dictionary<uint, ModifyDamageByFactionCommandDef> _modifyDamageByFactionCommandDef;
    private static Dictionary<uint, ModifyDamageByHeadshotCommandDef> _modifyDamageByHeadshotCommandDef;
    private static Dictionary<uint, ModifyDamageByMyHealthCommandDef> _modifyDamageByMyHealthCommandDef;
    private static Dictionary<uint, ModifyDamageByTargetCommandDef> _modifyDamageByTargetCommandDef;
    private static Dictionary<uint, ModifyDamageByTargetDamageResponseCommandDef> _modifyDamageByTargetDamageResponseCommandDef;
    private static Dictionary<uint, ModifyDamageByTargetHealthCommandDef> _modifyDamageByTargetHealthCommandDef;
    private static Dictionary<uint, ModifyDamageByTypeCommandDef> _modifyDamageByTypeCommandDef;
    private static Dictionary<uint, ModifyDamageForInflictCommandDef> _modifyDamageForInflictCommandDef;
    private static Dictionary<uint, ModifyHostilityCommandDef> _modifyHostilityCommandDef;
    private static Dictionary<uint, ModifyOwnerResourcesCommandDef> _modifyOwnerResourcesCommandDef;
    private static Dictionary<uint, NetworkStealthCommandDef> _networkStealthCommandDef;
    private static Dictionary<uint, ReduceCooldownsCommandDef> _reduceCooldownsCommandDef;
    private static Dictionary<uint, RegisterAbilityTriggerCommandDef> _registerAbilityTriggerCommandDef;
    private static Dictionary<uint, RegisterEffectTagTriggerCommandDef> _registerEffectTagTriggerCommandDef;
    private static Dictionary<uint, RegisterHitTagTypeTriggerCommandDef> _registerHitTagTypeTriggerCommandDef;
    private static Dictionary<uint, RegisterTimedTriggerCommandDef> _registerTimedTriggerCommandDef;
    private static Dictionary<uint, RemoteAbilityCallCommandDef> _remoteAbilityCallCommandDef;
    private static Dictionary<uint, RemoveEffectByTagCommandDef> _removeEffectByTagCommandDef;
    private static Dictionary<uint, RemovePermanentEffectCommandDef> _removePermanentEffectCommandDef;
    private static Dictionary<uint, ReplenishableDurationCommandDef> _replenishableDurationCommandDef;
    private static Dictionary<uint, ReplenishEffectDurationCommandDef> _replenishEffectDurationCommandDef;
    private static Dictionary<uint, RepositionClonesCommandDef> _repositionClonesCommandDef;
    private static Dictionary<uint, ReputationModifierCommandDef> _reputationModifierCommandDef;
    private static Dictionary<uint, RequestArcJobsCommandDef> _requestArcJobsCommandDef;
    private static Dictionary<uint, RequireAbilityPhysicsCommandDef> _requireAbilityPhysicsCommandDef;
    private static Dictionary<uint, RequireAppliedUnlockCommandDef> _requireAppliedUnlockCommandDef;
    private static Dictionary<uint, RequireInitiatorExistsCommandDef> _requireInitiatorExistsCommandDef;
    private static Dictionary<uint, RequireLootStoreCommandDef> _requireLootStoreCommandDef;
    private static Dictionary<uint, ResetCooldownsCommandDef> _resetCooldownsCommandDef;
    private static Dictionary<uint, ResourceNodeScanDefCommandDef> _resourceNodeScanDefCommandDef;
    private static Dictionary<uint, SendTipMessageCommandDef> _sendTipMessageCommandDef;
    private static Dictionary<uint, SetDefaultDamageBonusCommandDef> _setDefaultDamageBonusCommandDef;
    private static Dictionary<uint, SetGuardianCommandDef> _setGuardianCommandDef;
    private static Dictionary<uint, SetInteractionTypeCommandDef> _setInteractionTypeCommandDef;
    private static Dictionary<uint, SetLookAtTargetCommandDef> _setLookAtTargetCommandDef;
    private static Dictionary<uint, SetPoweredStateCommandDef> _setPoweredStateCommandDef;
    private static Dictionary<uint, SetScopeBubbleCommandDef> _setScopeBubbleCommandDef;
    private static Dictionary<uint, SetVisualInfoIndexCommandDef> _setVisualInfoIndexCommandDef;
    private static Dictionary<uint, ShoppingInvitationCommandDef> _shoppingInvitationCommandDef;
    private static Dictionary<uint, ShowRewardScreenCommandDef> _showRewardScreenCommandDef;
    private static Dictionary<uint, SinAcquireCommandDef> _sinAcquireCommandDef;
    private static Dictionary<uint, SpawnLootCommandDef> _spawnLootCommandDef;
    private static Dictionary<uint, StartArcCommandDef> _startArcCommandDef;
    private static Dictionary<uint, TargetAiTargetCommandDef> _targetAiTargetCommandDef;
    private static Dictionary<uint, TargetBySinVulnerableCommandDef> _targetBySinVulnerableCommandDef;
    private static Dictionary<uint, TargetMyTinyObjectsCommandDef> _targetMyTinyObjectsCommandDef;
    private static Dictionary<uint, TargetOwnedDeployablesCommandDef> _targetOwnedDeployablesCommandDef;
    private static Dictionary<uint, TauntCommandDef> _tauntCommandDef;
    private static Dictionary<uint, TeleportCommandDef> _teleportCommandDef;
    private static Dictionary<uint, TemporaryEquipmentCommandDef> _temporaryEquipmentCommandDef;
    private static Dictionary<uint, TemporaryEquipmentStatMappingCommandDef> _temporaryEquipmentStatMappingCommandDef;
    private static Dictionary<uint, UnlockBattleframesCommandDef> _unlockBattleframesCommandDef;
    private static Dictionary<uint, UnlockCertsCommandDef> _unlockCertsCommandDef;
    private static Dictionary<uint, UnlockContentCommandDef> _unlockContentCommandDef;
    private static Dictionary<uint, UnlockDecalsCommandDef> _unlockDecalsCommandDef;
    private static Dictionary<uint, UnlockHeadAccessoriesCommandDef> _unlockHeadAccessoriesCommandDef;
    private static Dictionary<uint, UnlockOrnamentsCommandDef> _unlockOrnamentsCommandDef;
    private static Dictionary<uint, UnlockPatternsCommandDef> _unlockPatternsCommandDef;
    private static Dictionary<uint, UnlockTitlesCommandDef> _unlockTitlesCommandDef;
    private static Dictionary<uint, UnlockVisualOverridesCommandDef> _unlockVisualOverridesCommandDef;
    private static Dictionary<uint, UnlockWarpaintsCommandDef> _unlockWarpaintsCommandDef;
    private static Dictionary<uint, UnpackItemCommandDef> _unpackItemCommandDef;

    // custom
    private static Dictionary<uint, Dictionary<uint, Deployable>> _deployable;
    private static Dictionary<uint, Dictionary<uint, Melding>> _melding;
    private static Dictionary<uint, Dictionary<uint, Outpost>> _outpost;
    private static Dictionary<uint, Dictionary<uint, MeldingRepulsorDef>> _meldingRepulsor;
    private static Dictionary<uint, Dictionary<uint, LgvRaceDef>> _lgvRace;

    public static void Init()
    {
        var loader = new CustomDBLoader();

        // aptgss
        _authorizeTerminalCommandDef = loader.LoadAuthorizeTerminalCommandDef();
        _setGliderParametersCommandDef = loader.LoadSetGliderParametersCommandDef();
        _modifyPermissionCommandDef = loader.LoadModifyPermissionCommandDef();
        _impactRemoveEffectCommandDef = loader.LoadImpactRemoveEffectCommandDef();
        _deployableSpawnCommandDef = loader.LoadDeployableSpawnCommandDef();
        _encounterSignalCommandDef = loader.LoadEncounterSignalCommandDef();
        _encounterSpawnCommandDef = loader.LoadEncounterSpawnCommandDef();
        _mountVehicleCommandDef = loader.LoadMountVehicleCommandDef();
        _carryableObjectSpawnCommandDef = loader.LoadCarryableObjectSpawnCommandDef();
        _applySinCardCommandDef = loader.LoadApplySinCardCommandDef();
        _createSpawnPointCommandDef = loader.LoadCreateSpawnPointCommandDef();
        _abilityFinishedCommandDef = loader.LoadAbilityFinishedCommandDef();
        _activateAbilityTriggerCommandDef = loader.LoadActivateAbilityTriggerCommandDef();
        _addAccountGroupCommandDef = loader.LoadAddAccountGroupCommandDef();
        _addAppendageHealthPoolCommandDef = loader.LoadAddAppendageHealthPoolCommandDef();
        _addFactionReputationCommandDef = loader.LoadAddFactionReputationCommandDef();
        _addLootTableCommandDef = loader.LoadAddLootTableCommandDef();
        _abilitySlottedCommandDef = loader.LoadAbilitySlottedCommandDef();
        _activateMissionCommandDef = loader.LoadActivateMissionCommandDef();
        _activateSpawnTableCommandDef = loader.LoadActivateSpawnTableCommandDef();
        _cancelRopePullCommandDef = loader.LoadCancelRopePullCommandDef();
        _createAbilityObjectCommandDef = loader.LoadCreateAbilityObjectCommandDef();
        _deployableUpgradeCommandDef = loader.LoadDeployableUpgradeCommandDef();
        _destroyAbilityObjectCommandDef = loader.LoadDestroyAbilityObjectCommandDef();
        _executeCommandDef = loader.LoadExecuteCommandDef();
        _interactionCompletionTimeCommandDef = loader.LoadInteractionCompletionTimeCommandDef();
        _interactionInProgressCommandDef = loader.LoadInteractionInProgressCommandDef();
        _interruptCommandDef = loader.LoadInterruptCommandDef();
        _lifespanDurationCommandDef = loader.LoadLifespanDurationCommandDef();
        _matchMakingQueueCommandDef = loader.LoadMatchMakingQueueCommandDef();
        _nPCBehaviorChangeCommandDef = loader.LoadNPCBehaviorChangeCommandDef();
        _nPCDespawnCommandDef = loader.LoadNPCDespawnCommandDef();
        _nPCDroidModeChangeCommandDef = loader.LoadNPCDroidModeChangeCommandDef();
        _nPCEquipMonsterCommandDef = loader.LoadNPCEquipMonsterCommandDef();
        _nPCSpawnCommandDef = loader.LoadNPCSpawnCommandDef();
        _requireTryingToMoveCommandDef = loader.LoadRequireTryingToMoveCommandDef();
        _resetTraumaCommandDef = loader.LoadResetTraumaCommandDef();
        _restockAmmoCommandDef = loader.LoadRestockAmmoCommandDef();
        _reviveCommandDef = loader.LoadReviveCommandDef();
        _rewardAssistCommandDef = loader.LoadRewardAssistCommandDef();
        _setHostilityCommandDef = loader.LoadSetHostilityCommandDef();
        _setHoverParametersCommandDef = loader.LoadSetHoverParametersCommandDef();
        _setObjectLifespanCommandDef = loader.LoadSetObjectLifespanCommandDef();
        _setOrientationCommandDef = loader.LoadSetOrientationCommandDef();
        _setRespawnFlagsCommandDef = loader.LoadSetRespawnFlagsCommandDef();
        _setYawCommandDef = loader.LoadSetYawCommandDef();
        _sinLinkRevealCommandDef = loader.LoadSinLinkRevealCommandDef();
        _slotAbilityCommandDef = loader.LoadSlotAbilityCommandDef();
        _targetByExistsCommandDef = loader.LoadTargetByExistsCommandDef();
        _targetByNPCCommandDef = loader.LoadTargetByNPCCommandDef();
        _targetByNPCTypeCommandDef = loader.LoadTargetByNPCTypeCommandDef();
        _targetCharacterNPCsCommandDef = loader.LoadTargetCharacterNPCsCommandDef();
        _targetTinyObjectCommandDef = loader.LoadTargetTinyObjectCommandDef();
        _teleportInstanceCommandDef = loader.LoadTeleportInstanceCommandDef();
        _tinyObjectCreateCommandDef = loader.LoadTinyObjectCreateCommandDef();
        _tinyObjectDestroyCommandDef = loader.LoadTinyObjectDestroyCommandDef();
        _tinyObjectUpdateCommandDef = loader.LoadTinyObjectUpdateCommandDef();
        _turretControlCommandDef = loader.LoadTurretControlCommandDef();
        _updateSpawnTableCommandDef = loader.LoadUpdateSpawnTableCommandDef();
        _applyPermanentEffectCommandDef = loader.LoadApplyPermanentEffectCommandDef();
        _applyUnlockCommandDef = loader.LoadApplyUnlockCommandDef();
        _awardRedBeansCommandDef = loader.LoadAwardRedBeansCommandDef();
        _calculateTrajectoryCommandDef = loader.LoadCalculateTrajectoryCommandDef();
        _calldownVehicleCommandDef = loader.LoadCalldownVehicleCommandDef();
        _clearHostilityCommandDef = loader.LoadClearHostilityCommandDef();
        _consumeItemCommandDef = loader.LoadConsumeItemCommandDef();
        _damageFeedbackCommandDef = loader.LoadDamageFeedbackCommandDef();
        _damageItemSlotCommandDef = loader.LoadDamageItemSlotCommandDef();
        _dropAllCarryableCommandDef = loader.LoadDropAllCarryableCommandDef();
        _dropCarryableCommandDef = loader.LoadDropCarryableCommandDef();
        _enableInteractionCommandDef = loader.LoadEnableInteractionCommandDef();
        _equipLoadoutCommandDef = loader.LoadEquipLoadoutCommandDef();
        _fallToGroundCommandDef = loader.LoadFallToGroundCommandDef();
        _forceRespawnCommandDef = loader.LoadForceRespawnCommandDef();
        _grantOwnerItemCommandDef = loader.LoadGrantOwnerItemCommandDef();
        _hostilityHackCommandDef = loader.LoadHostilityHackCommandDef();
        _hostilityOverrideCommandDef = loader.LoadHostilityOverrideCommandDef();
        _inflictHitFeedbackCommandDef = loader.LoadInflictHitFeedbackCommandDef();
        _itemAttributeModifierCommandDef = loader.LoadItemAttributeModifierCommandDef();
        _meldingBubbleCommandDef = loader.LoadMeldingBubbleCommandDef();
        _mindControlCommandDef = loader.LoadMindControlCommandDef();
        _modifyDamageByFactionCommandDef = loader.LoadModifyDamageByFactionCommandDef();
        _modifyDamageByHeadshotCommandDef = loader.LoadModifyDamageByHeadshotCommandDef();
        _modifyDamageByMyHealthCommandDef = loader.LoadModifyDamageByMyHealthCommandDef();
        _modifyDamageByTargetCommandDef = loader.LoadModifyDamageByTargetCommandDef();
        _modifyDamageByTargetDamageResponseCommandDef = loader.LoadModifyDamageByTargetDamageResponseCommandDef();
        _modifyDamageByTargetHealthCommandDef = loader.LoadModifyDamageByTargetHealthCommandDef();
        _modifyDamageByTypeCommandDef = loader.LoadModifyDamageByTypeCommandDef();
        _modifyDamageForInflictCommandDef = loader.LoadModifyDamageForInflictCommandDef();
        _modifyHostilityCommandDef = loader.LoadModifyHostilityCommandDef();
        _modifyOwnerResourcesCommandDef = loader.LoadModifyOwnerResourcesCommandDef();
        _networkStealthCommandDef = loader.LoadNetworkStealthCommandDef();
        _reduceCooldownsCommandDef = loader.LoadReduceCooldownsCommandDef();
        _registerAbilityTriggerCommandDef = loader.LoadRegisterAbilityTriggerCommandDef();
        _registerEffectTagTriggerCommandDef = loader.LoadRegisterEffectTagTriggerCommandDef();
        _registerHitTagTypeTriggerCommandDef = loader.LoadRegisterHitTagTypeTriggerCommandDef();
        _registerTimedTriggerCommandDef = loader.LoadRegisterTimedTriggerCommandDef();
        _remoteAbilityCallCommandDef = loader.LoadRemoteAbilityCallCommandDef();
        _removeEffectByTagCommandDef = loader.LoadRemoveEffectByTagCommandDef();
        _removePermanentEffectCommandDef = loader.LoadRemovePermanentEffectCommandDef();
        _replenishableDurationCommandDef = loader.LoadReplenishableDurationCommandDef();
        _replenishEffectDurationCommandDef = loader.LoadReplenishEffectDurationCommandDef();
        _repositionClonesCommandDef = loader.LoadRepositionClonesCommandDef();
        _reputationModifierCommandDef = loader.LoadReputationModifierCommandDef();
        _requestArcJobsCommandDef = loader.LoadRequestArcJobsCommandDef();
        _requireAbilityPhysicsCommandDef = loader.LoadRequireAbilityPhysicsCommandDef();
        _requireAppliedUnlockCommandDef = loader.LoadRequireAppliedUnlockCommandDef();
        _requireInitiatorExistsCommandDef = loader.LoadRequireInitiatorExistsCommandDef();
        _requireLootStoreCommandDef = loader.LoadRequireLootStoreCommandDef();
        _resetCooldownsCommandDef = loader.LoadResetCooldownsCommandDef();
        _resourceNodeScanDefCommandDef = loader.LoadResourceNodeScanDefCommandDef();
        _sendTipMessageCommandDef = loader.LoadSendTipMessageCommandDef();
        _setDefaultDamageBonusCommandDef = loader.LoadSetDefaultDamageBonusCommandDef();
        _setGuardianCommandDef = loader.LoadSetGuardianCommandDef();
        _setInteractionTypeCommandDef = loader.LoadSetInteractionTypeCommandDef();
        _setLookAtTargetCommandDef = loader.LoadSetLookAtTargetCommandDef();
        _setPoweredStateCommandDef = loader.LoadSetPoweredStateCommandDef();
        _setScopeBubbleCommandDef = loader.LoadSetScopeBubbleCommandDef();
        _setVisualInfoIndexCommandDef = loader.LoadSetVisualInfoIndexCommandDef();
        _shoppingInvitationCommandDef = loader.LoadShoppingInvitationCommandDef();
        _showRewardScreenCommandDef = loader.LoadShowRewardScreenCommandDef();
        _sinAcquireCommandDef = loader.LoadSinAcquireCommandDef();
        _spawnLootCommandDef = loader.LoadSpawnLootCommandDef();
        _startArcCommandDef = loader.LoadStartArcCommandDef();
        _targetAiTargetCommandDef = loader.LoadTargetAiTargetCommandDef();
        _targetBySinVulnerableCommandDef = loader.LoadTargetBySinVulnerableCommandDef();
        _targetMyTinyObjectsCommandDef = loader.LoadTargetMyTinyObjectsCommandDef();
        _targetOwnedDeployablesCommandDef = loader.LoadTargetOwnedDeployablesCommandDef();
        _tauntCommandDef = loader.LoadTauntCommandDef();
        _teleportCommandDef = loader.LoadTeleportCommandDef();
        _temporaryEquipmentCommandDef = loader.LoadTemporaryEquipmentCommandDef();
        _temporaryEquipmentStatMappingCommandDef = loader.LoadTemporaryEquipmentStatMappingCommandDef();
        _unlockBattleframesCommandDef = loader.LoadUnlockBattleframesCommandDef();
        _unlockCertsCommandDef = loader.LoadUnlockCertsCommandDef();
        _unlockContentCommandDef = loader.LoadUnlockContentCommandDef();
        _unlockDecalsCommandDef = loader.LoadUnlockDecalsCommandDef();
        _unlockHeadAccessoriesCommandDef = loader.LoadUnlockHeadAccessoriesCommandDef();
        _unlockOrnamentsCommandDef = loader.LoadUnlockOrnamentsCommandDef();
        _unlockPatternsCommandDef = loader.LoadUnlockPatternsCommandDef();
        _unlockTitlesCommandDef = loader.LoadUnlockTitlesCommandDef();
        _unlockVisualOverridesCommandDef = loader.LoadUnlockVisualOverridesCommandDef();
        _unlockWarpaintsCommandDef = loader.LoadUnlockWarpaintsCommandDef();
        _unpackItemCommandDef = loader.LoadUnpackItemCommandDef();

        // custom
        _deployable = loader.LoadDeployable();
        _melding = loader.LoadMelding();
        _outpost = loader.LoadOutpost();
        _meldingRepulsor = loader.LoadMeldingRepulsor();
        _lgvRace = loader.LoadLgvRace();
    }

    // aptgss
    public static AuthorizeTerminalCommandDef GetAuthorizeTerminalCommandDef(uint id) => _authorizeTerminalCommandDef.GetValueOrDefault(id);
    public static SetGliderParametersCommandDef GetSetGliderParametersCommandDef(uint id) => _setGliderParametersCommandDef.GetValueOrDefault(id);
    public static ModifyPermissionCommandDef GetModifyPermissionCommandDef(uint id) => _modifyPermissionCommandDef.GetValueOrDefault(id);
    public static ImpactRemoveEffectCommandDef GetImpactRemoveEffectCommandDef(uint id) => _impactRemoveEffectCommandDef.GetValueOrDefault(id);
    public static DeployableSpawnCommandDef GetDeployableSpawnCommandDef(uint id) => _deployableSpawnCommandDef.GetValueOrDefault(id);
    public static EncounterSignalCommandDef GetEncounterSignalCommandDef(uint id) => _encounterSignalCommandDef.GetValueOrDefault(id);
    public static EncounterSpawnCommandDef GetEncounterSpawnCommandDef(uint id) => _encounterSpawnCommandDef.GetValueOrDefault(id);
    public static MountVehicleCommandDef GetMountVehicleCommandDef(uint id) => _mountVehicleCommandDef.GetValueOrDefault(id);
    public static CarryableObjectSpawnCommandDef GetCarryableObjectSpawnCommandDef(uint id) => _carryableObjectSpawnCommandDef.GetValueOrDefault(id);
    public static ApplySinCardCommandDef GetApplySinCardCommandDef(uint id) => _applySinCardCommandDef.GetValueOrDefault(id);
    public static CreateSpawnPointCommandDef GetCreateSpawnPointCommandDef(uint id) => _createSpawnPointCommandDef.GetValueOrDefault(id);
    public static AbilityFinishedCommandDef GetAbilityFinishedCommandDef(uint id) => _abilityFinishedCommandDef.GetValueOrDefault(id);
    public static ActivateAbilityTriggerCommandDef GetActivateAbilityTriggerCommandDef(uint id) => _activateAbilityTriggerCommandDef.GetValueOrDefault(id);
    public static AddAccountGroupCommandDef GetAddAccountGroupCommandDef(uint id) => _addAccountGroupCommandDef.GetValueOrDefault(id);
    public static AddAppendageHealthPoolCommandDef GetAddAppendageHealthPoolCommandDef(uint id) => _addAppendageHealthPoolCommandDef.GetValueOrDefault(id);
    public static AddFactionReputationCommandDef GetAddFactionReputationCommandDef(uint id) => _addFactionReputationCommandDef.GetValueOrDefault(id);
    public static AddLootTableCommandDef GetAddLootTableCommandDef(uint id) => _addLootTableCommandDef.GetValueOrDefault(id);
    public static AbilitySlottedCommandDef GetAbilitySlottedCommandDef(uint id) => _abilitySlottedCommandDef.GetValueOrDefault(id);
    public static ActivateMissionCommandDef GetActivateMissionCommandDef(uint id) => _activateMissionCommandDef.GetValueOrDefault(id);
    public static ActivateSpawnTableCommandDef GetActivateSpawnTableCommandDef(uint id) => _activateSpawnTableCommandDef.GetValueOrDefault(id);
    public static CancelRopePullCommandDef GetCancelRopePullCommandDef(uint id) => _cancelRopePullCommandDef.GetValueOrDefault(id);
    public static CreateAbilityObjectCommandDef GetCreateAbilityObjectCommandDef(uint id) => _createAbilityObjectCommandDef.GetValueOrDefault(id);
    public static DeployableUpgradeCommandDef GetDeployableUpgradeCommandDef(uint id) => _deployableUpgradeCommandDef.GetValueOrDefault(id);
    public static DestroyAbilityObjectCommandDef GetDestroyAbilityObjectCommandDef(uint id) => _destroyAbilityObjectCommandDef.GetValueOrDefault(id);
    public static ExecuteCommandDef GetExecuteCommandDef(uint id) => _executeCommandDef.GetValueOrDefault(id);
    public static InteractionCompletionTimeCommandDef GetInteractionCompletionTimeCommandDef(uint id) => _interactionCompletionTimeCommandDef.GetValueOrDefault(id);
    public static InteractionInProgressCommandDef GetInteractionInProgressCommandDef(uint id) => _interactionInProgressCommandDef.GetValueOrDefault(id);
    public static InterruptCommandDef GetInterruptCommandDef(uint id) => _interruptCommandDef.GetValueOrDefault(id);
    public static LifespanDurationCommandDef GetLifespanDurationCommandDef(uint id) => _lifespanDurationCommandDef.GetValueOrDefault(id);
    public static MatchMakingQueueCommandDef GetMatchMakingQueueCommandDef(uint id) => _matchMakingQueueCommandDef.GetValueOrDefault(id);
    public static NPCBehaviorChangeCommandDef GetNPCBehaviorChangeCommandDef(uint id) => _nPCBehaviorChangeCommandDef.GetValueOrDefault(id);
    public static NPCDespawnCommandDef GetNPCDespawnCommandDef(uint id) => _nPCDespawnCommandDef.GetValueOrDefault(id);
    public static NPCDroidModeChangeCommandDef GetNPCDroidModeChangeCommandDef(uint id) => _nPCDroidModeChangeCommandDef.GetValueOrDefault(id);
    public static NPCEquipMonsterCommandDef GetNPCEquipMonsterCommandDef(uint id) => _nPCEquipMonsterCommandDef.GetValueOrDefault(id);
    public static NPCSpawnCommandDef GetNPCSpawnCommandDef(uint id) => _nPCSpawnCommandDef.GetValueOrDefault(id);
    public static RequireTryingToMoveCommandDef GetRequireTryingToMoveCommandDef(uint id) => _requireTryingToMoveCommandDef.GetValueOrDefault(id);
    public static ResetTraumaCommandDef GetResetTraumaCommandDef(uint id) => _resetTraumaCommandDef.GetValueOrDefault(id);
    public static RestockAmmoCommandDef GetRestockAmmoCommandDef(uint id) => _restockAmmoCommandDef.GetValueOrDefault(id);
    public static ReviveCommandDef GetReviveCommandDef(uint id) => _reviveCommandDef.GetValueOrDefault(id);
    public static RewardAssistCommandDef GetRewardAssistCommandDef(uint id) => _rewardAssistCommandDef.GetValueOrDefault(id);
    public static SetHostilityCommandDef GetSetHostilityCommandDef(uint id) => _setHostilityCommandDef.GetValueOrDefault(id);
    public static SetHoverParametersCommandDef GetSetHoverParametersCommandDef(uint id) => _setHoverParametersCommandDef.GetValueOrDefault(id);
    public static SetObjectLifespanCommandDef GetSetObjectLifespanCommandDef(uint id) => _setObjectLifespanCommandDef.GetValueOrDefault(id);
    public static SetOrientationCommandDef GetSetOrientationCommandDef(uint id) => _setOrientationCommandDef.GetValueOrDefault(id);
    public static SetRespawnFlagsCommandDef GetSetRespawnFlagsCommandDef(uint id) => _setRespawnFlagsCommandDef.GetValueOrDefault(id);
    public static SetYawCommandDef GetSetYawCommandDef(uint id) => _setYawCommandDef.GetValueOrDefault(id);
    public static SinLinkRevealCommandDef GetSinLinkRevealCommandDef(uint id) => _sinLinkRevealCommandDef.GetValueOrDefault(id);
    public static SlotAbilityCommandDef GetSlotAbilityCommandDef(uint id) => _slotAbilityCommandDef.GetValueOrDefault(id);
    public static TargetByExistsCommandDef GetTargetByExistsCommandDef(uint id) => _targetByExistsCommandDef.GetValueOrDefault(id);
    public static TargetByNPCCommandDef GetTargetByNPCCommandDef(uint id) => _targetByNPCCommandDef.GetValueOrDefault(id);
    public static TargetByNPCTypeCommandDef GetTargetByNPCTypeCommandDef(uint id) => _targetByNPCTypeCommandDef.GetValueOrDefault(id);
    public static TargetCharacterNPCsCommandDef GetTargetCharacterNPCsCommandDef(uint id) => _targetCharacterNPCsCommandDef.GetValueOrDefault(id);
    public static TargetTinyObjectCommandDef GetTargetTinyObjectCommandDef(uint id) => _targetTinyObjectCommandDef.GetValueOrDefault(id);
    public static TeleportInstanceCommandDef GetTeleportInstanceCommandDef(uint id) => _teleportInstanceCommandDef.GetValueOrDefault(id);
    public static TinyObjectCreateCommandDef GetTinyObjectCreateCommandDef(uint id) => _tinyObjectCreateCommandDef.GetValueOrDefault(id);
    public static TinyObjectDestroyCommandDef GetTinyObjectDestroyCommandDef(uint id) => _tinyObjectDestroyCommandDef.GetValueOrDefault(id);
    public static TinyObjectUpdateCommandDef GetTinyObjectUpdateCommandDef(uint id) => _tinyObjectUpdateCommandDef.GetValueOrDefault(id);
    public static TurretControlCommandDef GetTurretControlCommandDef(uint id) => _turretControlCommandDef.GetValueOrDefault(id);
    public static UpdateSpawnTableCommandDef GetUpdateSpawnTableCommandDef(uint id) => _updateSpawnTableCommandDef.GetValueOrDefault(id);
    public static ApplyPermanentEffectCommandDef GetApplyPermanentEffectCommandDef(uint id) => _applyPermanentEffectCommandDef.GetValueOrDefault(id);
    public static ApplyUnlockCommandDef GetApplyUnlockCommandDef(uint id) => _applyUnlockCommandDef.GetValueOrDefault(id);
    public static AwardRedBeansCommandDef GetAwardRedBeansCommandDef(uint id) => _awardRedBeansCommandDef.GetValueOrDefault(id);
    public static CalculateTrajectoryCommandDef GetCalculateTrajectoryCommandDef(uint id) => _calculateTrajectoryCommandDef.GetValueOrDefault(id);
    public static CalldownVehicleCommandDef GetCalldownVehicleCommandDef(uint id) => _calldownVehicleCommandDef.GetValueOrDefault(id);
    public static ClearHostilityCommandDef GetClearHostilityCommandDef(uint id) => _clearHostilityCommandDef.GetValueOrDefault(id);
    public static ConsumeItemCommandDef GetConsumeItemCommandDef(uint id) => _consumeItemCommandDef.GetValueOrDefault(id);
    public static DamageFeedbackCommandDef GetDamageFeedbackCommandDef(uint id) => _damageFeedbackCommandDef.GetValueOrDefault(id);
    public static DamageItemSlotCommandDef GetDamageItemSlotCommandDef(uint id) => _damageItemSlotCommandDef.GetValueOrDefault(id);
    public static DropAllCarryableCommandDef GetDropAllCarryableCommandDef(uint id) => _dropAllCarryableCommandDef.GetValueOrDefault(id);
    public static DropCarryableCommandDef GetDropCarryableCommandDef(uint id) => _dropCarryableCommandDef.GetValueOrDefault(id);
    public static EnableInteractionCommandDef GetEnableInteractionCommandDef(uint id) => _enableInteractionCommandDef.GetValueOrDefault(id);
    public static EquipLoadoutCommandDef GetEquipLoadoutCommandDef(uint id) => _equipLoadoutCommandDef.GetValueOrDefault(id);
    public static FallToGroundCommandDef GetFallToGroundCommandDef(uint id) => _fallToGroundCommandDef.GetValueOrDefault(id);
    public static ForceRespawnCommandDef GetForceRespawnCommandDef(uint id) => _forceRespawnCommandDef.GetValueOrDefault(id);
    public static GrantOwnerItemCommandDef GetGrantOwnerItemCommandDef(uint id) => _grantOwnerItemCommandDef.GetValueOrDefault(id);
    public static HostilityHackCommandDef GetHostilityHackCommandDef(uint id) => _hostilityHackCommandDef.GetValueOrDefault(id);
    public static HostilityOverrideCommandDef GetHostilityOverrideCommandDef(uint id) => _hostilityOverrideCommandDef.GetValueOrDefault(id);
    public static InflictHitFeedbackCommandDef GetInflictHitFeedbackCommandDef(uint id) => _inflictHitFeedbackCommandDef.GetValueOrDefault(id);
    public static ItemAttributeModifierCommandDef GetItemAttributeModifierCommandDef(uint id) => _itemAttributeModifierCommandDef.GetValueOrDefault(id);
    public static MeldingBubbleCommandDef GetMeldingBubbleCommandDef(uint id) => _meldingBubbleCommandDef.GetValueOrDefault(id);
    public static MindControlCommandDef GetMindControlCommandDef(uint id) => _mindControlCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByFactionCommandDef GetModifyDamageByFactionCommandDef(uint id) => _modifyDamageByFactionCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByHeadshotCommandDef GetModifyDamageByHeadshotCommandDef(uint id) => _modifyDamageByHeadshotCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByMyHealthCommandDef GetModifyDamageByMyHealthCommandDef(uint id) => _modifyDamageByMyHealthCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTargetCommandDef GetModifyDamageByTargetCommandDef(uint id) => _modifyDamageByTargetCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTargetDamageResponseCommandDef GetModifyDamageByTargetDamageResponseCommandDef(uint id) => _modifyDamageByTargetDamageResponseCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTargetHealthCommandDef GetModifyDamageByTargetHealthCommandDef(uint id) => _modifyDamageByTargetHealthCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTypeCommandDef GetModifyDamageByTypeCommandDef(uint id) => _modifyDamageByTypeCommandDef.GetValueOrDefault(id);
    public static ModifyDamageForInflictCommandDef GetModifyDamageForInflictCommandDef(uint id) => _modifyDamageForInflictCommandDef.GetValueOrDefault(id);
    public static ModifyHostilityCommandDef GetModifyHostilityCommandDef(uint id) => _modifyHostilityCommandDef.GetValueOrDefault(id);
    public static ModifyOwnerResourcesCommandDef GetModifyOwnerResourcesCommandDef(uint id) => _modifyOwnerResourcesCommandDef.GetValueOrDefault(id);
    public static NetworkStealthCommandDef GetNetworkStealthCommandDef(uint id) => _networkStealthCommandDef.GetValueOrDefault(id);
    public static ReduceCooldownsCommandDef GetReduceCooldownsCommandDef(uint id) => _reduceCooldownsCommandDef.GetValueOrDefault(id);
    public static RegisterAbilityTriggerCommandDef GetRegisterAbilityTriggerCommandDef(uint id) => _registerAbilityTriggerCommandDef.GetValueOrDefault(id);
    public static RegisterEffectTagTriggerCommandDef GetRegisterEffectTagTriggerCommandDef(uint id) => _registerEffectTagTriggerCommandDef.GetValueOrDefault(id);
    public static RegisterHitTagTypeTriggerCommandDef GetRegisterHitTagTypeTriggerCommandDef(uint id) => _registerHitTagTypeTriggerCommandDef.GetValueOrDefault(id);
    public static RegisterTimedTriggerCommandDef GetRegisterTimedTriggerCommandDef(uint id) => _registerTimedTriggerCommandDef.GetValueOrDefault(id);
    public static RemoteAbilityCallCommandDef GetRemoteAbilityCallCommandDef(uint id) => _remoteAbilityCallCommandDef.GetValueOrDefault(id);
    public static RemoveEffectByTagCommandDef GetRemoveEffectByTagCommandDef(uint id) => _removeEffectByTagCommandDef.GetValueOrDefault(id);
    public static RemovePermanentEffectCommandDef GetRemovePermanentEffectCommandDef(uint id) => _removePermanentEffectCommandDef.GetValueOrDefault(id);
    public static ReplenishableDurationCommandDef GetReplenishableDurationCommandDef(uint id) => _replenishableDurationCommandDef.GetValueOrDefault(id);
    public static ReplenishEffectDurationCommandDef GetReplenishEffectDurationCommandDef(uint id) => _replenishEffectDurationCommandDef.GetValueOrDefault(id);
    public static RepositionClonesCommandDef GetRepositionClonesCommandDef(uint id) => _repositionClonesCommandDef.GetValueOrDefault(id);
    public static ReputationModifierCommandDef GetReputationModifierCommandDef(uint id) => _reputationModifierCommandDef.GetValueOrDefault(id);
    public static RequestArcJobsCommandDef GetRequestArcJobsCommandDef(uint id) => _requestArcJobsCommandDef.GetValueOrDefault(id);
    public static RequireAbilityPhysicsCommandDef GetRequireAbilityPhysicsCommandDef(uint id) => _requireAbilityPhysicsCommandDef.GetValueOrDefault(id);
    public static RequireAppliedUnlockCommandDef GetRequireAppliedUnlockCommandDef(uint id) => _requireAppliedUnlockCommandDef.GetValueOrDefault(id);
    public static RequireInitiatorExistsCommandDef GetRequireInitiatorExistsCommandDef(uint id) => _requireInitiatorExistsCommandDef.GetValueOrDefault(id);
    public static RequireLootStoreCommandDef GetRequireLootStoreCommandDef(uint id) => _requireLootStoreCommandDef.GetValueOrDefault(id);
    public static ResetCooldownsCommandDef GetResetCooldownsCommandDef(uint id) => _resetCooldownsCommandDef.GetValueOrDefault(id);
    public static ResourceNodeScanDefCommandDef GetResourceNodeScanDefCommandDef(uint id) => _resourceNodeScanDefCommandDef.GetValueOrDefault(id);
    public static SendTipMessageCommandDef GetSendTipMessageCommandDef(uint id) => _sendTipMessageCommandDef.GetValueOrDefault(id);
    public static SetDefaultDamageBonusCommandDef GetSetDefaultDamageBonusCommandDef(uint id) => _setDefaultDamageBonusCommandDef.GetValueOrDefault(id);
    public static SetGuardianCommandDef GetSetGuardianCommandDef(uint id) => _setGuardianCommandDef.GetValueOrDefault(id);
    public static SetInteractionTypeCommandDef GetSetInteractionTypeCommandDef(uint id) => _setInteractionTypeCommandDef.GetValueOrDefault(id);
    public static SetLookAtTargetCommandDef GetSetLookAtTargetCommandDef(uint id) => _setLookAtTargetCommandDef.GetValueOrDefault(id);
    public static SetPoweredStateCommandDef GetSetPoweredStateCommandDef(uint id) => _setPoweredStateCommandDef.GetValueOrDefault(id);
    public static SetScopeBubbleCommandDef GetSetScopeBubbleCommandDef(uint id) => _setScopeBubbleCommandDef.GetValueOrDefault(id);
    public static SetVisualInfoIndexCommandDef GetSetVisualInfoIndexCommandDef(uint id) => _setVisualInfoIndexCommandDef.GetValueOrDefault(id);
    public static ShoppingInvitationCommandDef GetShoppingInvitationCommandDef(uint id) => _shoppingInvitationCommandDef.GetValueOrDefault(id);
    public static ShowRewardScreenCommandDef GetShowRewardScreenCommandDef(uint id) => _showRewardScreenCommandDef.GetValueOrDefault(id);
    public static SinAcquireCommandDef GetSinAcquireCommandDef(uint id) => _sinAcquireCommandDef.GetValueOrDefault(id);
    public static SpawnLootCommandDef GetSpawnLootCommandDef(uint id) => _spawnLootCommandDef.GetValueOrDefault(id);
    public static StartArcCommandDef GetStartArcCommandDef(uint id) => _startArcCommandDef.GetValueOrDefault(id);
    public static TargetAiTargetCommandDef GetTargetAiTargetCommandDef(uint id) => _targetAiTargetCommandDef.GetValueOrDefault(id);
    public static TargetBySinVulnerableCommandDef GetTargetBySinVulnerableCommandDef(uint id) => _targetBySinVulnerableCommandDef.GetValueOrDefault(id);
    public static TargetMyTinyObjectsCommandDef GetTargetMyTinyObjectsCommandDef(uint id) => _targetMyTinyObjectsCommandDef.GetValueOrDefault(id);
    public static TargetOwnedDeployablesCommandDef GetTargetOwnedDeployablesCommandDef(uint id) => _targetOwnedDeployablesCommandDef.GetValueOrDefault(id);
    public static TauntCommandDef GetTauntCommandDef(uint id) => _tauntCommandDef.GetValueOrDefault(id);
    public static TeleportCommandDef GetTeleportCommandDef(uint id) => _teleportCommandDef.GetValueOrDefault(id);
    public static TemporaryEquipmentCommandDef GetTemporaryEquipmentCommandDef(uint id) => _temporaryEquipmentCommandDef.GetValueOrDefault(id);
    public static TemporaryEquipmentStatMappingCommandDef GetTemporaryEquipmentStatMappingCommandDef(uint id) => _temporaryEquipmentStatMappingCommandDef.GetValueOrDefault(id);
    public static UnlockBattleframesCommandDef GetUnlockBattleframesCommandDef(uint id) => _unlockBattleframesCommandDef.GetValueOrDefault(id);
    public static UnlockCertsCommandDef GetUnlockCertsCommandDef(uint id) => _unlockCertsCommandDef.GetValueOrDefault(id);
    public static UnlockContentCommandDef GetUnlockContentCommandDef(uint id) => _unlockContentCommandDef.GetValueOrDefault(id);
    public static UnlockDecalsCommandDef GetUnlockDecalsCommandDef(uint id) => _unlockDecalsCommandDef.GetValueOrDefault(id);
    public static UnlockHeadAccessoriesCommandDef GetUnlockHeadAccessoriesCommandDef(uint id) => _unlockHeadAccessoriesCommandDef.GetValueOrDefault(id);
    public static UnlockOrnamentsCommandDef GetUnlockOrnamentsCommandDef(uint id) => _unlockOrnamentsCommandDef.GetValueOrDefault(id);
    public static UnlockPatternsCommandDef GetUnlockPatternsCommandDef(uint id) => _unlockPatternsCommandDef.GetValueOrDefault(id);
    public static UnlockTitlesCommandDef GetUnlockTitlesCommandDef(uint id) => _unlockTitlesCommandDef.GetValueOrDefault(id);
    public static UnlockVisualOverridesCommandDef GetUnlockVisualOverridesCommandDef(uint id) => _unlockVisualOverridesCommandDef.GetValueOrDefault(id);
    public static UnlockWarpaintsCommandDef GetUnlockWarpaintsCommandDef(uint id) => _unlockWarpaintsCommandDef.GetValueOrDefault(id);
    public static UnpackItemCommandDef GetUnpackItemCommandDef(uint id) => _unpackItemCommandDef.GetValueOrDefault(id);

    // custom
    public static Dictionary<uint, Deployable> GetZoneDeployables(uint zoneId) => _deployable.GetValueOrDefault(zoneId) ?? [];
    public static Dictionary<uint, Melding> GetZoneMeldings(uint zoneId) => _melding.GetValueOrDefault(zoneId) ?? [];
    public static Dictionary<uint, Outpost> GetZoneOutposts(uint zoneId) => _outpost.GetValueOrDefault(zoneId) ?? [];
    public static Dictionary<uint, MeldingRepulsorDef> GetZoneMeldingRepulsors(uint zoneId) => _meldingRepulsor.GetValueOrDefault(zoneId) ?? [];
    public static Dictionary<uint, LgvRaceDef> GetZoneLgvRaces(uint zoneId) => _lgvRace.GetValueOrDefault(zoneId) ?? [];
}