namespace GameServer.Data.SDB;

using System.Collections.Generic;
using Records.customdata;

public class CustomDBInterface
{
    // aptgss
    private static Dictionary<uint, AuthorizeTerminalCommandDef> AuthorizeTerminalCommandDef;
    private static Dictionary<uint, SetGliderParametersCommandDef> SetGliderParametersCommandDef;
    private static Dictionary<uint, ModifyPermissionCommandDef> ModifyPermissionCommandDef;
    private static Dictionary<uint, ImpactRemoveEffectCommandDef> ImpactRemoveEffectCommandDef;
    private static Dictionary<uint, DeployableSpawnCommandDef> DeployableSpawnCommandDef;
    private static Dictionary<uint, EncounterSignalCommandDef> EncounterSignalCommandDef;
    private static Dictionary<uint, EncounterSpawnCommandDef> EncounterSpawnCommandDef;
    private static Dictionary<uint, MountVehicleCommandDef> MountVehicleCommandDef;
    private static Dictionary<uint, CarryableObjectSpawnCommandDef> CarryableObjectSpawnCommandDef;
    private static Dictionary<uint, ApplySinCardCommandDef> ApplySinCardCommandDef;
    private static Dictionary<uint, CreateSpawnPointCommandDef> CreateSpawnPointCommandDef;
    private static Dictionary<uint, AbilityFinishedCommandDef> AbilityFinishedCommandDef;
    private static Dictionary<uint, ActivateAbilityTriggerCommandDef> ActivateAbilityTriggerCommandDef;
    private static Dictionary<uint, AddAccountGroupCommandDef> AddAccountGroupCommandDef;
    private static Dictionary<uint, AddAppendageHealthPoolCommandDef> AddAppendageHealthPoolCommandDef;
    private static Dictionary<uint, AddFactionReputationCommandDef> AddFactionReputationCommandDef;
    private static Dictionary<uint, AddLootTableCommandDef> AddLootTableCommandDef;
    private static Dictionary<uint, AbilitySlottedCommandDef> AbilitySlottedCommandDef;
    private static Dictionary<uint, ActivateMissionCommandDef> ActivateMissionCommandDef;
    private static Dictionary<uint, ActivateSpawnTableCommandDef> ActivateSpawnTableCommandDef;
    private static Dictionary<uint, CancelRopePullCommandDef> CancelRopePullCommandDef;
    private static Dictionary<uint, CreateAbilityObjectCommandDef> CreateAbilityObjectCommandDef;
    private static Dictionary<uint, DeployableUpgradeCommandDef> DeployableUpgradeCommandDef;
    private static Dictionary<uint, DestroyAbilityObjectCommandDef> DestroyAbilityObjectCommandDef;
    private static Dictionary<uint, ExecuteCommandDef> ExecuteCommandDef;
    private static Dictionary<uint, InteractionCompletionTimeCommandDef> InteractionCompletionTimeCommandDef;
    private static Dictionary<uint, InteractionInProgressCommandDef> InteractionInProgressCommandDef;
    private static Dictionary<uint, InterruptCommandDef> InterruptCommandDef;
    private static Dictionary<uint, LifespanDurationCommandDef> LifespanDurationCommandDef;
    private static Dictionary<uint, MatchMakingQueueCommandDef> MatchMakingQueueCommandDef;
    private static Dictionary<uint, NPCBehaviorChangeCommandDef> NPCBehaviorChangeCommandDef;
    private static Dictionary<uint, NPCDespawnCommandDef> NPCDespawnCommandDef;
    private static Dictionary<uint, NPCDroidModeChangeCommandDef> NPCDroidModeChangeCommandDef;
    private static Dictionary<uint, NPCEquipMonsterCommandDef> NPCEquipMonsterCommandDef;
    private static Dictionary<uint, NPCSpawnCommandDef> NPCSpawnCommandDef;
    private static Dictionary<uint, RequireTryingToMoveCommandDef> RequireTryingToMoveCommandDef;
    private static Dictionary<uint, ResetTraumaCommandDef> ResetTraumaCommandDef;
    private static Dictionary<uint, RestockAmmoCommandDef> RestockAmmoCommandDef;
    private static Dictionary<uint, ReviveCommandDef> ReviveCommandDef;
    private static Dictionary<uint, RewardAssistCommandDef> RewardAssistCommandDef;
    private static Dictionary<uint, SetHostilityCommandDef> SetHostilityCommandDef;
    private static Dictionary<uint, SetHoverParametersCommandDef> SetHoverParametersCommandDef;
    private static Dictionary<uint, SetObjectLifespanCommandDef> SetObjectLifespanCommandDef;
    private static Dictionary<uint, SetOrientationCommandDef> SetOrientationCommandDef;
    private static Dictionary<uint, SetRespawnFlagsCommandDef> SetRespawnFlagsCommandDef;
    private static Dictionary<uint, SetYawCommandDef> SetYawCommandDef;
    private static Dictionary<uint, SinLinkRevealCommandDef> SinLinkRevealCommandDef;
    private static Dictionary<uint, SlotAbilityCommandDef> SlotAbilityCommandDef;
    private static Dictionary<uint, TargetByExistsCommandDef> TargetByExistsCommandDef;
    private static Dictionary<uint, TargetByNPCCommandDef> TargetByNPCCommandDef;
    private static Dictionary<uint, TargetByNPCTypeCommandDef> TargetByNPCTypeCommandDef;
    private static Dictionary<uint, TargetCharacterNPCsCommandDef> TargetCharacterNPCsCommandDef;
    private static Dictionary<uint, TargetTinyObjectCommandDef> TargetTinyObjectCommandDef;
    private static Dictionary<uint, TeleportInstanceCommandDef> TeleportInstanceCommandDef;
    private static Dictionary<uint, TinyObjectCreateCommandDef> TinyObjectCreateCommandDef;
    private static Dictionary<uint, TinyObjectDestroyCommandDef> TinyObjectDestroyCommandDef;
    private static Dictionary<uint, TinyObjectUpdateCommandDef> TinyObjectUpdateCommandDef;
    private static Dictionary<uint, TurretControlCommandDef> TurretControlCommandDef;
    private static Dictionary<uint, UpdateSpawnTableCommandDef> UpdateSpawnTableCommandDef;
    private static Dictionary<uint, ApplyPermanentEffectCommandDef> ApplyPermanentEffectCommandDef;
    private static Dictionary<uint, ApplyUnlockCommandDef> ApplyUnlockCommandDef;
    private static Dictionary<uint, AwardRedBeansCommandDef> AwardRedBeansCommandDef;
    private static Dictionary<uint, CalculateTrajectoryCommandDef> CalculateTrajectoryCommandDef;
    private static Dictionary<uint, CalldownVehicleCommandDef> CalldownVehicleCommandDef;
    private static Dictionary<uint, ClearHostilityCommandDef> ClearHostilityCommandDef;
    private static Dictionary<uint, ConsumeItemCommandDef> ConsumeItemCommandDef;
    private static Dictionary<uint, DamageFeedbackCommandDef> DamageFeedbackCommandDef;
    private static Dictionary<uint, DamageItemSlotCommandDef> DamageItemSlotCommandDef;
    private static Dictionary<uint, DropAllCarryableCommandDef> DropAllCarryableCommandDef;
    private static Dictionary<uint, DropCarryableCommandDef> DropCarryableCommandDef;
    private static Dictionary<uint, EnableInteractionCommandDef> EnableInteractionCommandDef;
    private static Dictionary<uint, EquipLoadoutCommandDef> EquipLoadoutCommandDef;
    private static Dictionary<uint, FallToGroundCommandDef> FallToGroundCommandDef;
    private static Dictionary<uint, ForceRespawnCommandDef> ForceRespawnCommandDef;
    private static Dictionary<uint, GrantOwnerItemCommandDef> GrantOwnerItemCommandDef;
    private static Dictionary<uint, HostilityHackCommandDef> HostilityHackCommandDef;
    private static Dictionary<uint, HostilityOverrideCommandDef> HostilityOverrideCommandDef;
    private static Dictionary<uint, InflictHitFeedbackCommandDef> InflictHitFeedbackCommandDef;
    private static Dictionary<uint, ItemAttributeModifierCommandDef> ItemAttributeModifierCommandDef;
    private static Dictionary<uint, MeldingBubbleCommandDef> MeldingBubbleCommandDef;
    private static Dictionary<uint, MindControlCommandDef> MindControlCommandDef;
    private static Dictionary<uint, ModifyDamageByFactionCommandDef> ModifyDamageByFactionCommandDef;
    private static Dictionary<uint, ModifyDamageByHeadshotCommandDef> ModifyDamageByHeadshotCommandDef;
    private static Dictionary<uint, ModifyDamageByMyHealthCommandDef> ModifyDamageByMyHealthCommandDef;
    private static Dictionary<uint, ModifyDamageByTargetCommandDef> ModifyDamageByTargetCommandDef;
    private static Dictionary<uint, ModifyDamageByTargetDamageResponseCommandDef> ModifyDamageByTargetDamageResponseCommandDef;
    private static Dictionary<uint, ModifyDamageByTargetHealthCommandDef> ModifyDamageByTargetHealthCommandDef;
    private static Dictionary<uint, ModifyDamageByTypeCommandDef> ModifyDamageByTypeCommandDef;
    private static Dictionary<uint, ModifyDamageForInflictCommandDef> ModifyDamageForInflictCommandDef;
    private static Dictionary<uint, ModifyHostilityCommandDef> ModifyHostilityCommandDef;
    private static Dictionary<uint, ModifyOwnerResourcesCommandDef> ModifyOwnerResourcesCommandDef;
    private static Dictionary<uint, NetworkStealthCommandDef> NetworkStealthCommandDef;
    private static Dictionary<uint, ReduceCooldownsCommandDef> ReduceCooldownsCommandDef;
    private static Dictionary<uint, RegisterAbilityTriggerCommandDef> RegisterAbilityTriggerCommandDef;
    private static Dictionary<uint, RegisterEffectTagTriggerCommandDef> RegisterEffectTagTriggerCommandDef;
    private static Dictionary<uint, RegisterHitTagTypeTriggerCommandDef> RegisterHitTagTypeTriggerCommandDef;
    private static Dictionary<uint, RegisterTimedTriggerCommandDef> RegisterTimedTriggerCommandDef;
    private static Dictionary<uint, RemoteAbilityCallCommandDef> RemoteAbilityCallCommandDef;
    private static Dictionary<uint, RemoveEffectByTagCommandDef> RemoveEffectByTagCommandDef;
    private static Dictionary<uint, RemovePermanentEffectCommandDef> RemovePermanentEffectCommandDef;
    private static Dictionary<uint, ReplenishableDurationCommandDef> ReplenishableDurationCommandDef;
    private static Dictionary<uint, ReplenishEffectDurationCommandDef> ReplenishEffectDurationCommandDef;
    private static Dictionary<uint, RepositionClonesCommandDef> RepositionClonesCommandDef;
    private static Dictionary<uint, ReputationModifierCommandDef> ReputationModifierCommandDef;
    private static Dictionary<uint, RequestArcJobsCommandDef> RequestArcJobsCommandDef;
    private static Dictionary<uint, RequireAbilityPhysicsCommandDef> RequireAbilityPhysicsCommandDef;
    private static Dictionary<uint, RequireAppliedUnlockCommandDef> RequireAppliedUnlockCommandDef;
    private static Dictionary<uint, RequireInitiatorExistsCommandDef> RequireInitiatorExistsCommandDef;
    private static Dictionary<uint, RequireLootStoreCommandDef> RequireLootStoreCommandDef;
    private static Dictionary<uint, ResetCooldownsCommandDef> ResetCooldownsCommandDef;
    private static Dictionary<uint, ResourceNodeScanDefCommandDef> ResourceNodeScanDefCommandDef;
    private static Dictionary<uint, SendTipMessageCommandDef> SendTipMessageCommandDef;
    private static Dictionary<uint, SetDefaultDamageBonusCommandDef> SetDefaultDamageBonusCommandDef;
    private static Dictionary<uint, SetGuardianCommandDef> SetGuardianCommandDef;
    private static Dictionary<uint, SetInteractionTypeCommandDef> SetInteractionTypeCommandDef;
    private static Dictionary<uint, SetLookAtTargetCommandDef> SetLookAtTargetCommandDef;
    private static Dictionary<uint, SetPoweredStateCommandDef> SetPoweredStateCommandDef;
    private static Dictionary<uint, SetScopeBubbleCommandDef> SetScopeBubbleCommandDef;
    private static Dictionary<uint, SetVisualInfoIndexCommandDef> SetVisualInfoIndexCommandDef;
    private static Dictionary<uint, ShoppingInvitationCommandDef> ShoppingInvitationCommandDef;
    private static Dictionary<uint, ShowRewardScreenCommandDef> ShowRewardScreenCommandDef;
    private static Dictionary<uint, SinAcquireCommandDef> SinAcquireCommandDef;
    private static Dictionary<uint, SpawnLootCommandDef> SpawnLootCommandDef;
    private static Dictionary<uint, StartArcCommandDef> StartArcCommandDef;
    private static Dictionary<uint, TargetAiTargetCommandDef> TargetAiTargetCommandDef;
    private static Dictionary<uint, TargetBySinVulnerableCommandDef> TargetBySinVulnerableCommandDef;
    private static Dictionary<uint, TargetMyTinyObjectsCommandDef> TargetMyTinyObjectsCommandDef;
    private static Dictionary<uint, TargetOwnedDeployablesCommandDef> TargetOwnedDeployablesCommandDef;
    private static Dictionary<uint, TauntCommandDef> TauntCommandDef;
    private static Dictionary<uint, TeleportCommandDef> TeleportCommandDef;
    private static Dictionary<uint, TemporaryEquipmentCommandDef> TemporaryEquipmentCommandDef;
    private static Dictionary<uint, TemporaryEquipmentStatMappingCommandDef> TemporaryEquipmentStatMappingCommandDef;
    private static Dictionary<uint, UnlockBattleframesCommandDef> UnlockBattleframesCommandDef;
    private static Dictionary<uint, UnlockCertsCommandDef> UnlockCertsCommandDef;
    private static Dictionary<uint, UnlockContentCommandDef> UnlockContentCommandDef;
    private static Dictionary<uint, UnlockDecalsCommandDef> UnlockDecalsCommandDef;
    private static Dictionary<uint, UnlockHeadAccessoriesCommandDef> UnlockHeadAccessoriesCommandDef;
    private static Dictionary<uint, UnlockOrnamentsCommandDef> UnlockOrnamentsCommandDef;
    private static Dictionary<uint, UnlockPatternsCommandDef> UnlockPatternsCommandDef;
    private static Dictionary<uint, UnlockTitlesCommandDef> UnlockTitlesCommandDef;
    private static Dictionary<uint, UnlockVisualOverridesCommandDef> UnlockVisualOverridesCommandDef;
    private static Dictionary<uint, UnlockWarpaintsCommandDef> UnlockWarpaintsCommandDef;
    private static Dictionary<uint, UnpackItemCommandDef> UnpackItemCommandDef;

    // custom
    private static Dictionary<uint, Dictionary<uint, Deployable>> Deployable;
    private static Dictionary<uint, Dictionary<uint, Melding>> Melding;
    private static Dictionary<uint, Dictionary<uint, Outpost>> Outpost;

    public static void Init()
    {
        var loader = new CustomDBLoader();

        // aptgss
        AuthorizeTerminalCommandDef = loader.LoadAuthorizeTerminalCommandDef();
        SetGliderParametersCommandDef = loader.LoadSetGliderParametersCommandDef();
        ModifyPermissionCommandDef = loader.LoadModifyPermissionCommandDef();
        ImpactRemoveEffectCommandDef = loader.LoadImpactRemoveEffectCommandDef();
        DeployableSpawnCommandDef = loader.LoadDeployableSpawnCommandDef();
        EncounterSignalCommandDef = loader.LoadEncounterSignalCommandDef();
        EncounterSpawnCommandDef = loader.LoadEncounterSpawnCommandDef();
        MountVehicleCommandDef = loader.LoadMountVehicleCommandDef();
        CarryableObjectSpawnCommandDef = loader.LoadCarryableObjectSpawnCommandDef();
        ApplySinCardCommandDef = loader.LoadApplySinCardCommandDef();
        CreateSpawnPointCommandDef = loader.LoadCreateSpawnPointCommandDef();
        AbilityFinishedCommandDef = loader.LoadAbilityFinishedCommandDef();
        ActivateAbilityTriggerCommandDef = loader.LoadActivateAbilityTriggerCommandDef();
        AddAccountGroupCommandDef = loader.LoadAddAccountGroupCommandDef();
        AddAppendageHealthPoolCommandDef = loader.LoadAddAppendageHealthPoolCommandDef();
        AddFactionReputationCommandDef = loader.LoadAddFactionReputationCommandDef();
        AddLootTableCommandDef = loader.LoadAddLootTableCommandDef();
        AbilitySlottedCommandDef = loader.LoadAbilitySlottedCommandDef();
        ActivateMissionCommandDef = loader.LoadActivateMissionCommandDef();
        ActivateSpawnTableCommandDef = loader.LoadActivateSpawnTableCommandDef();
        CancelRopePullCommandDef = loader.LoadCancelRopePullCommandDef();
        CreateAbilityObjectCommandDef = loader.LoadCreateAbilityObjectCommandDef();
        DeployableUpgradeCommandDef = loader.LoadDeployableUpgradeCommandDef();
        DestroyAbilityObjectCommandDef = loader.LoadDestroyAbilityObjectCommandDef();
        ExecuteCommandDef = loader.LoadExecuteCommandDef();
        InteractionCompletionTimeCommandDef = loader.LoadInteractionCompletionTimeCommandDef();
        InteractionInProgressCommandDef = loader.LoadInteractionInProgressCommandDef();
        InterruptCommandDef = loader.LoadInterruptCommandDef();
        LifespanDurationCommandDef = loader.LoadLifespanDurationCommandDef();
        MatchMakingQueueCommandDef = loader.LoadMatchMakingQueueCommandDef();
        NPCBehaviorChangeCommandDef = loader.LoadNPCBehaviorChangeCommandDef();
        NPCDespawnCommandDef = loader.LoadNPCDespawnCommandDef();
        NPCDroidModeChangeCommandDef = loader.LoadNPCDroidModeChangeCommandDef();
        NPCEquipMonsterCommandDef = loader.LoadNPCEquipMonsterCommandDef();
        NPCSpawnCommandDef = loader.LoadNPCSpawnCommandDef();
        RequireTryingToMoveCommandDef = loader.LoadRequireTryingToMoveCommandDef();
        ResetTraumaCommandDef = loader.LoadResetTraumaCommandDef();
        RestockAmmoCommandDef = loader.LoadRestockAmmoCommandDef();
        ReviveCommandDef = loader.LoadReviveCommandDef();
        RewardAssistCommandDef = loader.LoadRewardAssistCommandDef();
        SetHostilityCommandDef = loader.LoadSetHostilityCommandDef();
        SetHoverParametersCommandDef = loader.LoadSetHoverParametersCommandDef();
        SetObjectLifespanCommandDef = loader.LoadSetObjectLifespanCommandDef();
        SetOrientationCommandDef = loader.LoadSetOrientationCommandDef();
        SetRespawnFlagsCommandDef = loader.LoadSetRespawnFlagsCommandDef();
        SetYawCommandDef = loader.LoadSetYawCommandDef();
        SinLinkRevealCommandDef = loader.LoadSinLinkRevealCommandDef();
        SlotAbilityCommandDef = loader.LoadSlotAbilityCommandDef();
        TargetByExistsCommandDef = loader.LoadTargetByExistsCommandDef();
        TargetByNPCCommandDef = loader.LoadTargetByNPCCommandDef();
        TargetByNPCTypeCommandDef = loader.LoadTargetByNPCTypeCommandDef();
        TargetCharacterNPCsCommandDef = loader.LoadTargetCharacterNPCsCommandDef();
        TargetTinyObjectCommandDef = loader.LoadTargetTinyObjectCommandDef();
        TeleportInstanceCommandDef = loader.LoadTeleportInstanceCommandDef();
        TinyObjectCreateCommandDef = loader.LoadTinyObjectCreateCommandDef();
        TinyObjectDestroyCommandDef = loader.LoadTinyObjectDestroyCommandDef();
        TinyObjectUpdateCommandDef = loader.LoadTinyObjectUpdateCommandDef();
        TurretControlCommandDef = loader.LoadTurretControlCommandDef();
        UpdateSpawnTableCommandDef = loader.LoadUpdateSpawnTableCommandDef();
        ApplyPermanentEffectCommandDef = loader.LoadApplyPermanentEffectCommandDef();
        ApplyUnlockCommandDef = loader.LoadApplyUnlockCommandDef();
        AwardRedBeansCommandDef = loader.LoadAwardRedBeansCommandDef();
        CalculateTrajectoryCommandDef = loader.LoadCalculateTrajectoryCommandDef();
        CalldownVehicleCommandDef = loader.LoadCalldownVehicleCommandDef();
        ClearHostilityCommandDef = loader.LoadClearHostilityCommandDef();
        ConsumeItemCommandDef = loader.LoadConsumeItemCommandDef();
        DamageFeedbackCommandDef = loader.LoadDamageFeedbackCommandDef();
        DamageItemSlotCommandDef = loader.LoadDamageItemSlotCommandDef();
        DropAllCarryableCommandDef = loader.LoadDropAllCarryableCommandDef();
        DropCarryableCommandDef = loader.LoadDropCarryableCommandDef();
        EnableInteractionCommandDef = loader.LoadEnableInteractionCommandDef();
        EquipLoadoutCommandDef = loader.LoadEquipLoadoutCommandDef();
        FallToGroundCommandDef = loader.LoadFallToGroundCommandDef();
        ForceRespawnCommandDef = loader.LoadForceRespawnCommandDef();
        GrantOwnerItemCommandDef = loader.LoadGrantOwnerItemCommandDef();
        HostilityHackCommandDef = loader.LoadHostilityHackCommandDef();
        HostilityOverrideCommandDef = loader.LoadHostilityOverrideCommandDef();
        InflictHitFeedbackCommandDef = loader.LoadInflictHitFeedbackCommandDef();
        ItemAttributeModifierCommandDef = loader.LoadItemAttributeModifierCommandDef();
        MeldingBubbleCommandDef = loader.LoadMeldingBubbleCommandDef();
        MindControlCommandDef = loader.LoadMindControlCommandDef();
        ModifyDamageByFactionCommandDef = loader.LoadModifyDamageByFactionCommandDef();
        ModifyDamageByHeadshotCommandDef = loader.LoadModifyDamageByHeadshotCommandDef();
        ModifyDamageByMyHealthCommandDef = loader.LoadModifyDamageByMyHealthCommandDef();
        ModifyDamageByTargetCommandDef = loader.LoadModifyDamageByTargetCommandDef();
        ModifyDamageByTargetDamageResponseCommandDef = loader.LoadModifyDamageByTargetDamageResponseCommandDef();
        ModifyDamageByTargetHealthCommandDef = loader.LoadModifyDamageByTargetHealthCommandDef();
        ModifyDamageByTypeCommandDef = loader.LoadModifyDamageByTypeCommandDef();
        ModifyDamageForInflictCommandDef = loader.LoadModifyDamageForInflictCommandDef();
        ModifyHostilityCommandDef = loader.LoadModifyHostilityCommandDef();
        ModifyOwnerResourcesCommandDef = loader.LoadModifyOwnerResourcesCommandDef();
        NetworkStealthCommandDef = loader.LoadNetworkStealthCommandDef();
        ReduceCooldownsCommandDef = loader.LoadReduceCooldownsCommandDef();
        RegisterAbilityTriggerCommandDef = loader.LoadRegisterAbilityTriggerCommandDef();
        RegisterEffectTagTriggerCommandDef = loader.LoadRegisterEffectTagTriggerCommandDef();
        RegisterHitTagTypeTriggerCommandDef = loader.LoadRegisterHitTagTypeTriggerCommandDef();
        RegisterTimedTriggerCommandDef = loader.LoadRegisterTimedTriggerCommandDef();
        RemoteAbilityCallCommandDef = loader.LoadRemoteAbilityCallCommandDef();
        RemoveEffectByTagCommandDef = loader.LoadRemoveEffectByTagCommandDef();
        RemovePermanentEffectCommandDef = loader.LoadRemovePermanentEffectCommandDef();
        ReplenishableDurationCommandDef = loader.LoadReplenishableDurationCommandDef();
        ReplenishEffectDurationCommandDef = loader.LoadReplenishEffectDurationCommandDef();
        RepositionClonesCommandDef = loader.LoadRepositionClonesCommandDef();
        ReputationModifierCommandDef = loader.LoadReputationModifierCommandDef();
        RequestArcJobsCommandDef = loader.LoadRequestArcJobsCommandDef();
        RequireAbilityPhysicsCommandDef = loader.LoadRequireAbilityPhysicsCommandDef();
        RequireAppliedUnlockCommandDef = loader.LoadRequireAppliedUnlockCommandDef();
        RequireInitiatorExistsCommandDef = loader.LoadRequireInitiatorExistsCommandDef();
        RequireLootStoreCommandDef = loader.LoadRequireLootStoreCommandDef();
        ResetCooldownsCommandDef = loader.LoadResetCooldownsCommandDef();
        ResourceNodeScanDefCommandDef = loader.LoadResourceNodeScanDefCommandDef();
        SendTipMessageCommandDef = loader.LoadSendTipMessageCommandDef();
        SetDefaultDamageBonusCommandDef = loader.LoadSetDefaultDamageBonusCommandDef();
        SetGuardianCommandDef = loader.LoadSetGuardianCommandDef();
        SetInteractionTypeCommandDef = loader.LoadSetInteractionTypeCommandDef();
        SetLookAtTargetCommandDef = loader.LoadSetLookAtTargetCommandDef();
        SetPoweredStateCommandDef = loader.LoadSetPoweredStateCommandDef();
        SetScopeBubbleCommandDef = loader.LoadSetScopeBubbleCommandDef();
        SetVisualInfoIndexCommandDef = loader.LoadSetVisualInfoIndexCommandDef();
        ShoppingInvitationCommandDef = loader.LoadShoppingInvitationCommandDef();
        ShowRewardScreenCommandDef = loader.LoadShowRewardScreenCommandDef();
        SinAcquireCommandDef = loader.LoadSinAcquireCommandDef();
        SpawnLootCommandDef = loader.LoadSpawnLootCommandDef();
        StartArcCommandDef = loader.LoadStartArcCommandDef();
        TargetAiTargetCommandDef = loader.LoadTargetAiTargetCommandDef();
        TargetBySinVulnerableCommandDef = loader.LoadTargetBySinVulnerableCommandDef();
        TargetMyTinyObjectsCommandDef = loader.LoadTargetMyTinyObjectsCommandDef();
        TargetOwnedDeployablesCommandDef = loader.LoadTargetOwnedDeployablesCommandDef();
        TauntCommandDef = loader.LoadTauntCommandDef();
        TeleportCommandDef = loader.LoadTeleportCommandDef();
        TemporaryEquipmentCommandDef = loader.LoadTemporaryEquipmentCommandDef();
        TemporaryEquipmentStatMappingCommandDef = loader.LoadTemporaryEquipmentStatMappingCommandDef();
        UnlockBattleframesCommandDef = loader.LoadUnlockBattleframesCommandDef();
        UnlockCertsCommandDef = loader.LoadUnlockCertsCommandDef();
        UnlockContentCommandDef = loader.LoadUnlockContentCommandDef();
        UnlockDecalsCommandDef = loader.LoadUnlockDecalsCommandDef();
        UnlockHeadAccessoriesCommandDef = loader.LoadUnlockHeadAccessoriesCommandDef();
        UnlockOrnamentsCommandDef = loader.LoadUnlockOrnamentsCommandDef();
        UnlockPatternsCommandDef = loader.LoadUnlockPatternsCommandDef();
        UnlockTitlesCommandDef = loader.LoadUnlockTitlesCommandDef();
        UnlockVisualOverridesCommandDef = loader.LoadUnlockVisualOverridesCommandDef();
        UnlockWarpaintsCommandDef = loader.LoadUnlockWarpaintsCommandDef();
        UnpackItemCommandDef = loader.LoadUnpackItemCommandDef();

        // custom
        Deployable = loader.LoadDeployable();
        Melding = loader.LoadMelding();
        Outpost = loader.LoadOutpost();
    }

    // aptgss
    public static AuthorizeTerminalCommandDef GetAuthorizeTerminalCommandDef(uint id) => AuthorizeTerminalCommandDef.GetValueOrDefault(id);
    public static SetGliderParametersCommandDef GetSetGliderParametersCommandDef(uint id) => SetGliderParametersCommandDef.GetValueOrDefault(id);
    public static ModifyPermissionCommandDef GetModifyPermissionCommandDef(uint id) => ModifyPermissionCommandDef.GetValueOrDefault(id);
    public static ImpactRemoveEffectCommandDef GetImpactRemoveEffectCommandDef(uint id) => ImpactRemoveEffectCommandDef.GetValueOrDefault(id);
    public static DeployableSpawnCommandDef GetDeployableSpawnCommandDef(uint id) => DeployableSpawnCommandDef.GetValueOrDefault(id);
    public static EncounterSignalCommandDef GetEncounterSignalCommandDef(uint id) => EncounterSignalCommandDef.GetValueOrDefault(id);
    public static EncounterSpawnCommandDef GetEncounterSpawnCommandDef(uint id) => EncounterSpawnCommandDef.GetValueOrDefault(id);
    public static MountVehicleCommandDef GetMountVehicleCommandDef(uint id) => MountVehicleCommandDef.GetValueOrDefault(id);
    public static CarryableObjectSpawnCommandDef GetCarryableObjectSpawnCommandDef(uint id) => CarryableObjectSpawnCommandDef.GetValueOrDefault(id);
    public static ApplySinCardCommandDef GetApplySinCardCommandDef(uint id) => ApplySinCardCommandDef.GetValueOrDefault(id);
    public static CreateSpawnPointCommandDef GetCreateSpawnPointCommandDef(uint id) => CreateSpawnPointCommandDef.GetValueOrDefault(id);
    public static AbilityFinishedCommandDef GetAbilityFinishedCommandDef(uint id) => AbilityFinishedCommandDef.GetValueOrDefault(id);
    public static ActivateAbilityTriggerCommandDef GetActivateAbilityTriggerCommandDef(uint id) => ActivateAbilityTriggerCommandDef.GetValueOrDefault(id);
    public static AddAccountGroupCommandDef GetAddAccountGroupCommandDef(uint id) => AddAccountGroupCommandDef.GetValueOrDefault(id);
    public static AddAppendageHealthPoolCommandDef GetAddAppendageHealthPoolCommandDef(uint id) => AddAppendageHealthPoolCommandDef.GetValueOrDefault(id);
    public static AddFactionReputationCommandDef GetAddFactionReputationCommandDef(uint id) => AddFactionReputationCommandDef.GetValueOrDefault(id);
    public static AddLootTableCommandDef GetAddLootTableCommandDef(uint id) => AddLootTableCommandDef.GetValueOrDefault(id);
    public static AbilitySlottedCommandDef GetAbilitySlottedCommandDef(uint id) => AbilitySlottedCommandDef.GetValueOrDefault(id);
    public static ActivateMissionCommandDef GetActivateMissionCommandDef(uint id) => ActivateMissionCommandDef.GetValueOrDefault(id);
    public static ActivateSpawnTableCommandDef GetActivateSpawnTableCommandDef(uint id) => ActivateSpawnTableCommandDef.GetValueOrDefault(id);
    public static CancelRopePullCommandDef GetCancelRopePullCommandDef(uint id) => CancelRopePullCommandDef.GetValueOrDefault(id);
    public static CreateAbilityObjectCommandDef GetCreateAbilityObjectCommandDef(uint id) => CreateAbilityObjectCommandDef.GetValueOrDefault(id);
    public static DeployableUpgradeCommandDef GetDeployableUpgradeCommandDef(uint id) => DeployableUpgradeCommandDef.GetValueOrDefault(id);
    public static DestroyAbilityObjectCommandDef GetDestroyAbilityObjectCommandDef(uint id) => DestroyAbilityObjectCommandDef.GetValueOrDefault(id);
    public static ExecuteCommandDef GetExecuteCommandDef(uint id) => ExecuteCommandDef.GetValueOrDefault(id);
    public static InteractionCompletionTimeCommandDef GetInteractionCompletionTimeCommandDef(uint id) => InteractionCompletionTimeCommandDef.GetValueOrDefault(id);
    public static InteractionInProgressCommandDef GetInteractionInProgressCommandDef(uint id) => InteractionInProgressCommandDef.GetValueOrDefault(id);
    public static InterruptCommandDef GetInterruptCommandDef(uint id) => InterruptCommandDef.GetValueOrDefault(id);
    public static LifespanDurationCommandDef GetLifespanDurationCommandDef(uint id) => LifespanDurationCommandDef.GetValueOrDefault(id);
    public static MatchMakingQueueCommandDef GetMatchMakingQueueCommandDef(uint id) => MatchMakingQueueCommandDef.GetValueOrDefault(id);
    public static NPCBehaviorChangeCommandDef GetNPCBehaviorChangeCommandDef(uint id) => NPCBehaviorChangeCommandDef.GetValueOrDefault(id);
    public static NPCDespawnCommandDef GetNPCDespawnCommandDef(uint id) => NPCDespawnCommandDef.GetValueOrDefault(id);
    public static NPCDroidModeChangeCommandDef GetNPCDroidModeChangeCommandDef(uint id) => NPCDroidModeChangeCommandDef.GetValueOrDefault(id);
    public static NPCEquipMonsterCommandDef GetNPCEquipMonsterCommandDef(uint id) => NPCEquipMonsterCommandDef.GetValueOrDefault(id);
    public static NPCSpawnCommandDef GetNPCSpawnCommandDef(uint id) => NPCSpawnCommandDef.GetValueOrDefault(id);
    public static RequireTryingToMoveCommandDef GetRequireTryingToMoveCommandDef(uint id) => RequireTryingToMoveCommandDef.GetValueOrDefault(id);
    public static ResetTraumaCommandDef GetResetTraumaCommandDef(uint id) => ResetTraumaCommandDef.GetValueOrDefault(id);
    public static RestockAmmoCommandDef GetRestockAmmoCommandDef(uint id) => RestockAmmoCommandDef.GetValueOrDefault(id);
    public static ReviveCommandDef GetReviveCommandDef(uint id) => ReviveCommandDef.GetValueOrDefault(id);
    public static RewardAssistCommandDef GetRewardAssistCommandDef(uint id) => RewardAssistCommandDef.GetValueOrDefault(id);
    public static SetHostilityCommandDef GetSetHostilityCommandDef(uint id) => SetHostilityCommandDef.GetValueOrDefault(id);
    public static SetHoverParametersCommandDef GetSetHoverParametersCommandDef(uint id) => SetHoverParametersCommandDef.GetValueOrDefault(id);
    public static SetObjectLifespanCommandDef GetSetObjectLifespanCommandDef(uint id) => SetObjectLifespanCommandDef.GetValueOrDefault(id);
    public static SetOrientationCommandDef GetSetOrientationCommandDef(uint id) => SetOrientationCommandDef.GetValueOrDefault(id);
    public static SetRespawnFlagsCommandDef GetSetRespawnFlagsCommandDef(uint id) => SetRespawnFlagsCommandDef.GetValueOrDefault(id);
    public static SetYawCommandDef GetSetYawCommandDef(uint id) => SetYawCommandDef.GetValueOrDefault(id);
    public static SinLinkRevealCommandDef GetSinLinkRevealCommandDef(uint id) => SinLinkRevealCommandDef.GetValueOrDefault(id);
    public static SlotAbilityCommandDef GetSlotAbilityCommandDef(uint id) => SlotAbilityCommandDef.GetValueOrDefault(id);
    public static TargetByExistsCommandDef GetTargetByExistsCommandDef(uint id) => TargetByExistsCommandDef.GetValueOrDefault(id);
    public static TargetByNPCCommandDef GetTargetByNPCCommandDef(uint id) => TargetByNPCCommandDef.GetValueOrDefault(id);
    public static TargetByNPCTypeCommandDef GetTargetByNPCTypeCommandDef(uint id) => TargetByNPCTypeCommandDef.GetValueOrDefault(id);
    public static TargetCharacterNPCsCommandDef GetTargetCharacterNPCsCommandDef(uint id) => TargetCharacterNPCsCommandDef.GetValueOrDefault(id);
    public static TargetTinyObjectCommandDef GetTargetTinyObjectCommandDef(uint id) => TargetTinyObjectCommandDef.GetValueOrDefault(id);
    public static TeleportInstanceCommandDef GetTeleportInstanceCommandDef(uint id) => TeleportInstanceCommandDef.GetValueOrDefault(id);
    public static TinyObjectCreateCommandDef GetTinyObjectCreateCommandDef(uint id) => TinyObjectCreateCommandDef.GetValueOrDefault(id);
    public static TinyObjectDestroyCommandDef GetTinyObjectDestroyCommandDef(uint id) => TinyObjectDestroyCommandDef.GetValueOrDefault(id);
    public static TinyObjectUpdateCommandDef GetTinyObjectUpdateCommandDef(uint id) => TinyObjectUpdateCommandDef.GetValueOrDefault(id);
    public static TurretControlCommandDef GetTurretControlCommandDef(uint id) => TurretControlCommandDef.GetValueOrDefault(id);
    public static UpdateSpawnTableCommandDef GetUpdateSpawnTableCommandDef(uint id) => UpdateSpawnTableCommandDef.GetValueOrDefault(id);
    public static ApplyPermanentEffectCommandDef GetApplyPermanentEffectCommandDef(uint id) => ApplyPermanentEffectCommandDef.GetValueOrDefault(id);
    public static ApplyUnlockCommandDef GetApplyUnlockCommandDef(uint id) => ApplyUnlockCommandDef.GetValueOrDefault(id);
    public static AwardRedBeansCommandDef GetAwardRedBeansCommandDef(uint id) => AwardRedBeansCommandDef.GetValueOrDefault(id);
    public static CalculateTrajectoryCommandDef GetCalculateTrajectoryCommandDef(uint id) => CalculateTrajectoryCommandDef.GetValueOrDefault(id);
    public static CalldownVehicleCommandDef GetCalldownVehicleCommandDef(uint id) => CalldownVehicleCommandDef.GetValueOrDefault(id);
    public static ClearHostilityCommandDef GetClearHostilityCommandDef(uint id) => ClearHostilityCommandDef.GetValueOrDefault(id);
    public static ConsumeItemCommandDef GetConsumeItemCommandDef(uint id) => ConsumeItemCommandDef.GetValueOrDefault(id);
    public static DamageFeedbackCommandDef GetDamageFeedbackCommandDef(uint id) => DamageFeedbackCommandDef.GetValueOrDefault(id);
    public static DamageItemSlotCommandDef GetDamageItemSlotCommandDef(uint id) => DamageItemSlotCommandDef.GetValueOrDefault(id);
    public static DropAllCarryableCommandDef GetDropAllCarryableCommandDef(uint id) => DropAllCarryableCommandDef.GetValueOrDefault(id);
    public static DropCarryableCommandDef GetDropCarryableCommandDef(uint id) => DropCarryableCommandDef.GetValueOrDefault(id);
    public static EnableInteractionCommandDef GetEnableInteractionCommandDef(uint id) => EnableInteractionCommandDef.GetValueOrDefault(id);
    public static EquipLoadoutCommandDef GetEquipLoadoutCommandDef(uint id) => EquipLoadoutCommandDef.GetValueOrDefault(id);
    public static FallToGroundCommandDef GetFallToGroundCommandDef(uint id) => FallToGroundCommandDef.GetValueOrDefault(id);
    public static ForceRespawnCommandDef GetForceRespawnCommandDef(uint id) => ForceRespawnCommandDef.GetValueOrDefault(id);
    public static GrantOwnerItemCommandDef GetGrantOwnerItemCommandDef(uint id) => GrantOwnerItemCommandDef.GetValueOrDefault(id);
    public static HostilityHackCommandDef GetHostilityHackCommandDef(uint id) => HostilityHackCommandDef.GetValueOrDefault(id);
    public static HostilityOverrideCommandDef GetHostilityOverrideCommandDef(uint id) => HostilityOverrideCommandDef.GetValueOrDefault(id);
    public static InflictHitFeedbackCommandDef GetInflictHitFeedbackCommandDef(uint id) => InflictHitFeedbackCommandDef.GetValueOrDefault(id);
    public static ItemAttributeModifierCommandDef GetItemAttributeModifierCommandDef(uint id) => ItemAttributeModifierCommandDef.GetValueOrDefault(id);
    public static MeldingBubbleCommandDef GetMeldingBubbleCommandDef(uint id) => MeldingBubbleCommandDef.GetValueOrDefault(id);
    public static MindControlCommandDef GetMindControlCommandDef(uint id) => MindControlCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByFactionCommandDef GetModifyDamageByFactionCommandDef(uint id) => ModifyDamageByFactionCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByHeadshotCommandDef GetModifyDamageByHeadshotCommandDef(uint id) => ModifyDamageByHeadshotCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByMyHealthCommandDef GetModifyDamageByMyHealthCommandDef(uint id) => ModifyDamageByMyHealthCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTargetCommandDef GetModifyDamageByTargetCommandDef(uint id) => ModifyDamageByTargetCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTargetDamageResponseCommandDef GetModifyDamageByTargetDamageResponseCommandDef(uint id) => ModifyDamageByTargetDamageResponseCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTargetHealthCommandDef GetModifyDamageByTargetHealthCommandDef(uint id) => ModifyDamageByTargetHealthCommandDef.GetValueOrDefault(id);
    public static ModifyDamageByTypeCommandDef GetModifyDamageByTypeCommandDef(uint id) => ModifyDamageByTypeCommandDef.GetValueOrDefault(id);
    public static ModifyDamageForInflictCommandDef GetModifyDamageForInflictCommandDef(uint id) => ModifyDamageForInflictCommandDef.GetValueOrDefault(id);
    public static ModifyHostilityCommandDef GetModifyHostilityCommandDef(uint id) => ModifyHostilityCommandDef.GetValueOrDefault(id);
    public static ModifyOwnerResourcesCommandDef GetModifyOwnerResourcesCommandDef(uint id) => ModifyOwnerResourcesCommandDef.GetValueOrDefault(id);
    public static NetworkStealthCommandDef GetNetworkStealthCommandDef(uint id) => NetworkStealthCommandDef.GetValueOrDefault(id);
    public static ReduceCooldownsCommandDef GetReduceCooldownsCommandDef(uint id) => ReduceCooldownsCommandDef.GetValueOrDefault(id);
    public static RegisterAbilityTriggerCommandDef GetRegisterAbilityTriggerCommandDef(uint id) => RegisterAbilityTriggerCommandDef.GetValueOrDefault(id);
    public static RegisterEffectTagTriggerCommandDef GetRegisterEffectTagTriggerCommandDef(uint id) => RegisterEffectTagTriggerCommandDef.GetValueOrDefault(id);
    public static RegisterHitTagTypeTriggerCommandDef GetRegisterHitTagTypeTriggerCommandDef(uint id) => RegisterHitTagTypeTriggerCommandDef.GetValueOrDefault(id);
    public static RegisterTimedTriggerCommandDef GetRegisterTimedTriggerCommandDef(uint id) => RegisterTimedTriggerCommandDef.GetValueOrDefault(id);
    public static RemoteAbilityCallCommandDef GetRemoteAbilityCallCommandDef(uint id) => RemoteAbilityCallCommandDef.GetValueOrDefault(id);
    public static RemoveEffectByTagCommandDef GetRemoveEffectByTagCommandDef(uint id) => RemoveEffectByTagCommandDef.GetValueOrDefault(id);
    public static RemovePermanentEffectCommandDef GetRemovePermanentEffectCommandDef(uint id) => RemovePermanentEffectCommandDef.GetValueOrDefault(id);
    public static ReplenishableDurationCommandDef GetReplenishableDurationCommandDef(uint id) => ReplenishableDurationCommandDef.GetValueOrDefault(id);
    public static ReplenishEffectDurationCommandDef GetReplenishEffectDurationCommandDef(uint id) => ReplenishEffectDurationCommandDef.GetValueOrDefault(id);
    public static RepositionClonesCommandDef GetRepositionClonesCommandDef(uint id) => RepositionClonesCommandDef.GetValueOrDefault(id);
    public static ReputationModifierCommandDef GetReputationModifierCommandDef(uint id) => ReputationModifierCommandDef.GetValueOrDefault(id);
    public static RequestArcJobsCommandDef GetRequestArcJobsCommandDef(uint id) => RequestArcJobsCommandDef.GetValueOrDefault(id);
    public static RequireAbilityPhysicsCommandDef GetRequireAbilityPhysicsCommandDef(uint id) => RequireAbilityPhysicsCommandDef.GetValueOrDefault(id);
    public static RequireAppliedUnlockCommandDef GetRequireAppliedUnlockCommandDef(uint id) => RequireAppliedUnlockCommandDef.GetValueOrDefault(id);
    public static RequireInitiatorExistsCommandDef GetRequireInitiatorExistsCommandDef(uint id) => RequireInitiatorExistsCommandDef.GetValueOrDefault(id);
    public static RequireLootStoreCommandDef GetRequireLootStoreCommandDef(uint id) => RequireLootStoreCommandDef.GetValueOrDefault(id);
    public static ResetCooldownsCommandDef GetResetCooldownsCommandDef(uint id) => ResetCooldownsCommandDef.GetValueOrDefault(id);
    public static ResourceNodeScanDefCommandDef GetResourceNodeScanDefCommandDef(uint id) => ResourceNodeScanDefCommandDef.GetValueOrDefault(id);
    public static SendTipMessageCommandDef GetSendTipMessageCommandDef(uint id) => SendTipMessageCommandDef.GetValueOrDefault(id);
    public static SetDefaultDamageBonusCommandDef GetSetDefaultDamageBonusCommandDef(uint id) => SetDefaultDamageBonusCommandDef.GetValueOrDefault(id);
    public static SetGuardianCommandDef GetSetGuardianCommandDef(uint id) => SetGuardianCommandDef.GetValueOrDefault(id);
    public static SetInteractionTypeCommandDef GetSetInteractionTypeCommandDef(uint id) => SetInteractionTypeCommandDef.GetValueOrDefault(id);
    public static SetLookAtTargetCommandDef GetSetLookAtTargetCommandDef(uint id) => SetLookAtTargetCommandDef.GetValueOrDefault(id);
    public static SetPoweredStateCommandDef GetSetPoweredStateCommandDef(uint id) => SetPoweredStateCommandDef.GetValueOrDefault(id);
    public static SetScopeBubbleCommandDef GetSetScopeBubbleCommandDef(uint id) => SetScopeBubbleCommandDef.GetValueOrDefault(id);
    public static SetVisualInfoIndexCommandDef GetSetVisualInfoIndexCommandDef(uint id) => SetVisualInfoIndexCommandDef.GetValueOrDefault(id);
    public static ShoppingInvitationCommandDef GetShoppingInvitationCommandDef(uint id) => ShoppingInvitationCommandDef.GetValueOrDefault(id);
    public static ShowRewardScreenCommandDef GetShowRewardScreenCommandDef(uint id) => ShowRewardScreenCommandDef.GetValueOrDefault(id);
    public static SinAcquireCommandDef GetSinAcquireCommandDef(uint id) => SinAcquireCommandDef.GetValueOrDefault(id);
    public static SpawnLootCommandDef GetSpawnLootCommandDef(uint id) => SpawnLootCommandDef.GetValueOrDefault(id);
    public static StartArcCommandDef GetStartArcCommandDef(uint id) => StartArcCommandDef.GetValueOrDefault(id);
    public static TargetAiTargetCommandDef GetTargetAiTargetCommandDef(uint id) => TargetAiTargetCommandDef.GetValueOrDefault(id);
    public static TargetBySinVulnerableCommandDef GetTargetBySinVulnerableCommandDef(uint id) => TargetBySinVulnerableCommandDef.GetValueOrDefault(id);
    public static TargetMyTinyObjectsCommandDef GetTargetMyTinyObjectsCommandDef(uint id) => TargetMyTinyObjectsCommandDef.GetValueOrDefault(id);
    public static TargetOwnedDeployablesCommandDef GetTargetOwnedDeployablesCommandDef(uint id) => TargetOwnedDeployablesCommandDef.GetValueOrDefault(id);
    public static TauntCommandDef GetTauntCommandDef(uint id) => TauntCommandDef.GetValueOrDefault(id);
    public static TeleportCommandDef GetTeleportCommandDef(uint id) => TeleportCommandDef.GetValueOrDefault(id);
    public static TemporaryEquipmentCommandDef GetTemporaryEquipmentCommandDef(uint id) => TemporaryEquipmentCommandDef.GetValueOrDefault(id);
    public static TemporaryEquipmentStatMappingCommandDef GetTemporaryEquipmentStatMappingCommandDef(uint id) => TemporaryEquipmentStatMappingCommandDef.GetValueOrDefault(id);
    public static UnlockBattleframesCommandDef GetUnlockBattleframesCommandDef(uint id) => UnlockBattleframesCommandDef.GetValueOrDefault(id);
    public static UnlockCertsCommandDef GetUnlockCertsCommandDef(uint id) => UnlockCertsCommandDef.GetValueOrDefault(id);
    public static UnlockContentCommandDef GetUnlockContentCommandDef(uint id) => UnlockContentCommandDef.GetValueOrDefault(id);
    public static UnlockDecalsCommandDef GetUnlockDecalsCommandDef(uint id) => UnlockDecalsCommandDef.GetValueOrDefault(id);
    public static UnlockHeadAccessoriesCommandDef GetUnlockHeadAccessoriesCommandDef(uint id) => UnlockHeadAccessoriesCommandDef.GetValueOrDefault(id);
    public static UnlockOrnamentsCommandDef GetUnlockOrnamentsCommandDef(uint id) => UnlockOrnamentsCommandDef.GetValueOrDefault(id);
    public static UnlockPatternsCommandDef GetUnlockPatternsCommandDef(uint id) => UnlockPatternsCommandDef.GetValueOrDefault(id);
    public static UnlockTitlesCommandDef GetUnlockTitlesCommandDef(uint id) => UnlockTitlesCommandDef.GetValueOrDefault(id);
    public static UnlockVisualOverridesCommandDef GetUnlockVisualOverridesCommandDef(uint id) => UnlockVisualOverridesCommandDef.GetValueOrDefault(id);
    public static UnlockWarpaintsCommandDef GetUnlockWarpaintsCommandDef(uint id) => UnlockWarpaintsCommandDef.GetValueOrDefault(id);
    public static UnpackItemCommandDef GetUnpackItemCommandDef(uint id) => UnpackItemCommandDef.GetValueOrDefault(id);

    // custom
    public static Dictionary<uint, Deployable> GetZoneDeployables(uint zoneId) => Deployable.GetValueOrDefault(zoneId);
    public static Dictionary<uint, Melding> GetZoneMeldings(uint zoneId) => Melding.GetValueOrDefault(zoneId);
    public static Dictionary<uint, Outpost> GetZoneOutposts(uint zoneId) => Outpost.GetValueOrDefault(zoneId);
}